/* SPDX-License-Identifier: GPL-2.0-or-later */
#include "script_component.hpp"

class CfgPatches {
    class ADDON {
        name = COMPONENT_NAME;
        units[] = {};
        weapons[] = {};
        requiredVersion = 2.04;
        requiredAddons[] = {
            "aee_main",
            "aee_core",
            "aee_environmental",
            "aee_nightvision",
            "aee_thermal",
            "cba_main",
            "cba_xeh"
        };
        author = AUTHOR;
        authors[] = AUTHORS;
        url = URL;
        VERSION_CONFIG;
    };
};

// The AEE font families.  The converted .fxy glyph index and .paa glyph
// atlases are produced by the operator procedure in
// docs/wiki/research/arma-font-surface.md.  Until they exist the engine
// falls back to its default font, so the default state is unchanged.
class CfgFontFamilies {
    class AEEFont {
        fonts[] = {
            "z\aee\addons\optics\data\fonts\rajdhani\AEEFont9",
            "z\aee\addons\optics\data\fonts\rajdhani\AEEFont10",
            "z\aee\addons\optics\data\fonts\rajdhani\AEEFont11",
            "z\aee\addons\optics\data\fonts\rajdhani\AEEFont12"
        };
        spaceWidth = 0.9;
    };
    class AEEFontMono {
        fonts[] = {
            "z\aee\addons\optics\data\fonts\b612mono\AEEFontMono9",
            "z\aee\addons\optics\data\fonts\b612mono\AEEFontMono10",
            "z\aee\addons\optics\data\fonts\b612mono\AEEFontMono11",
            "z\aee\addons\optics\data\fonts\b612mono\AEEFontMono12"
        };
        spaceWidth = 0.5;
    };
};

// The map terrain palette and the object icons are included inside this block
// so the engine class is not declared twice.  The map grid font is NOT
// repointed here.  The AEE fonts need the FontToTGA operator step (see
// docs/wiki/research/arma-font-surface.md), and the engine draws no text for a
// family whose glyph files are absent, so the engine font stays until the AEE
// glyphs ship.  Re-point fontGrid and fontNames at AEEFont then.
//
// The engine grid fields SPLIT: colorGrid colours the EDGE COORDINATE NUMBERS
// and colorGridMap colours the in-map grid LINES (engine source: Poseidon
// UIMap.cpp, CStaticMap::DrawGrid - DrawText uses colorGrid, DrawLine uses
// colorGridMap).  The operator asked for the vanilla grid reference back, so the
// engine NUMBERS return (colorGrid visible, the engine default sizeExGrid 0.04)
// while the engine LINES stay off (colorGridMap alpha 0).  That leaves exactly
// ONE line grid, the AEE MGRS overlay (FUNC(mgrsMapDraw)), with the engine
// numeric labels as the familiar reference.  The two coexist: numbers from the
// engine, lines from AEE.
class RscMapControl {
#include "config_mapcolors.hpp"
#include "config_mapicons.hpp"
    colorGrid[] = {0.15, 0.15, 0.05, 0.9};
    colorGridMap[] = {0, 0, 0, 0};
    sizeExGrid = 0.04;
};

#include "config_locationtypes.hpp"
#include "config_mapdisplays.hpp"
#include "config_curator.hpp"

// ─── NATO/OPFOR map symbology markers (ADR-023) ──────────────────────────
// Real engine map markers.  Every AEE symbol is a CfgMarkers entry whose
// icon is a real .paa, so it is selectable in the marker dialog, placeable
// in Eden and drawn by the engine marker layer.  The name is
// AEE_<family>_<glyph>: the family is the affiliation (b friend, o hostile,
// n neutral, u unknown) and the glyph is the class category.  The engine's
// own NATO textures are referenced where they carry the symbol; the rest
// are produced by tools/gen_symbology_markers.py under data/markers.
class CfgMarkerClasses {
    // The engine marker picker is a flat list of CfgMarkerClasses.  AEE carries
    // the hierarchy the operator asked for with two levels in the class name and
    // the displayName: the CATEGORY is the affiliation and the SUBCATEGORY is the
    // battle dimension.  The three modifier groups are their own categories.  The
    // class names are generated by tools/symbology_categories.py and pinned by
    // tools/tests/test_symbology.py.
    class AEE_Friend_Land { displayName = "AEE Friend - Land"; };
    class AEE_Friend_Air { displayName = "AEE Friend - Air"; };
    class AEE_Friend_Sea { displayName = "AEE Friend - Sea"; };
    class AEE_Friend_Subsurface { displayName = "AEE Friend - Subsurface"; };
    class AEE_Friend_Installation { displayName = "AEE Friend - Installation"; };
    class AEE_Friend_Equipment { displayName = "AEE Friend - Equipment"; };
    class AEE_Friend_Other { displayName = "AEE Friend - Other"; };
    class AEE_Hostile_Land { displayName = "AEE Hostile - Land"; };
    class AEE_Hostile_Air { displayName = "AEE Hostile - Air"; };
    class AEE_Hostile_Sea { displayName = "AEE Hostile - Sea"; };
    class AEE_Hostile_Subsurface { displayName = "AEE Hostile - Subsurface"; };
    class AEE_Hostile_Installation { displayName = "AEE Hostile - Installation"; };
    class AEE_Hostile_Equipment { displayName = "AEE Hostile - Equipment"; };
    class AEE_Hostile_Other { displayName = "AEE Hostile - Other"; };
    class AEE_Neutral_Land { displayName = "AEE Neutral - Land"; };
    class AEE_Neutral_Air { displayName = "AEE Neutral - Air"; };
    class AEE_Neutral_Sea { displayName = "AEE Neutral - Sea"; };
    class AEE_Neutral_Subsurface { displayName = "AEE Neutral - Subsurface"; };
    class AEE_Neutral_Installation { displayName = "AEE Neutral - Installation"; };
    class AEE_Neutral_Equipment { displayName = "AEE Neutral - Equipment"; };
    class AEE_Neutral_Other { displayName = "AEE Neutral - Other"; };
    class AEE_Unknown_Land { displayName = "AEE Unknown - Land"; };
    class AEE_Unknown_Air { displayName = "AEE Unknown - Air"; };
    class AEE_Unknown_Sea { displayName = "AEE Unknown - Sea"; };
    class AEE_Unknown_Subsurface { displayName = "AEE Unknown - Subsurface"; };
    class AEE_Unknown_Installation { displayName = "AEE Unknown - Installation"; };
    class AEE_Unknown_Equipment { displayName = "AEE Unknown - Equipment"; };
    class AEE_Unknown_Other { displayName = "AEE Unknown - Other"; };
    class AEE_Mission_Tasks { displayName = "AEE Mission Tasks"; };
    class AEE_Modifiers { displayName = "AEE Modifiers"; };
    class AEE_Echelon { displayName = "AEE Echelon"; };
};

// The marker colour classes.  Every AEE marker texture carries its OWN colour
// (the affiliation frame, the black glyph and the standard fills), so the
// engine tint must be NEUTRAL: ColorAEE is white and leaves the texture's
// colours untouched.  The affiliation classes are kept because
// FUNC(symbologyAffiliation) reads a mission marker's original colour through
// them before AEE converts it.
class CfgMarkerColors {
    class ColorAEE { color[] = {1, 1, 1, 1}; };
    class ColorWEST { color[] = {0, 1, 1, 1}; };
    class ColorEAST { color[] = {1, 0, 0, 1}; };
    class ColorGUER { color[] = {0, 1, 0, 1}; };
    class ColorCIV { color[] = {1, 0, 1, 1}; };
    class ColorUNKNOWN { color[] = {1, 1, 0, 1}; };
};

class CfgMarkers {
    // Building block.  scope = 0, so it is never a usable icon on its own.
    class AEE_MarkerBase {
        scope = 0;
        // Every AEE symbol sets its own category; this default is a valid class
        // for the hand-written family aliases, whose category the runtime does
        // not read (they are selected by type name, not by the picker).
        markerClass = "AEE_Unknown_Other";
        size = 32;
        shadow = 0;
        // Neutral, so each texture shows its own colours (the colour IS the
        // information).  The engine tint is applied by setMarkerColorLocal;
        // ColorAEE is white.
        color[] = {1, 1, 1, 1};
        showEditorMarkerColor = 1;
    };

    // The complete AEE APP-6 marker set, generated from the pulled catalogue
    // by tools/gen_symbology_catalogue.py.  Do not edit by hand.
#include "config_markers.hpp"

    // The composed APP-6 cross-product: each real function glyph re-framed in
    // the four affiliation frames AEE draws from the APP-6 geometry, generated
    // by tools/gen_symbology_crossproduct.py.  Do not edit by hand.
#include "config_crossproduct.hpp"

    // The MIL-STD-2525 function glyphs the pulled catalogue does not hold,
    // rendered from the standard taxonomy by tools/gen_symbology_taxonomy.py.
    // Do not edit by hand.
#include "config_taxonomy.hpp"

    // The APP-6 mission-task graphics, the amplifier modifiers and the
    // echelon overlays, rendered by tools/gen_symbology_modifiers.py.  The
    // echelon overlay classes are selected at run time by the marker layer.
    // Do not edit by hand.
#include "config_modifiers.hpp"

    // The AEE runtime marker families returned by fnc_symbologyMarkerType.
    // Each inherits the real APP-6 catalogue symbol (or the AEE-produced
    // texture), so its side, category and scope come from the catalogue.
    // Do not edit by hand.
#include "config_family.hpp"
};

#include "CfgEventHandlers.hpp"
#include "RscTitles.hpp"

