#include "..\..\script_component.hpp"
/*
 * Fusion overlay (issue #204, Track B ENVG-B).
 *
 * Renders the physics-driven thermal state as an emissive overlay on
 * top of the NVG base view.  Real fusion goggles (L3Harris ENVG-B,
 * AN/PSQ-20) blend an image-intensified I2 tube image with a thermal
 * microbolometer image; the thermal channel is a separate composited
 * source, not the native TI mode.
 *
 * Mechanism (proven by the workshop audit - A3TI EmissiveWhite.rvmat,
 * workshop 2041057379): swap each object's thermal selections to an
 * rvmat whose EMISSIVE carries the heat.  A3TI uses a binary
 * full-white (emmisive 500, AlwaysInShadow, ambient 20) so everything
 * glows white over the NVG.  We grade it by the SAME physics + AGC
 * state as the thermal display: hotter selections glow brighter,
 * cooler selections stay dark.  The 256 generated fusion_emissive_NNN
 * rvmats carry emissive = band_grey * 500 (band_255 = full A3TI white), so
 * band_128 glows about half as bright.  The ladder is generated by
 * tools/gen_fusion_emissive_materials.py, so the count is auditable and the
 * set is reproducible.  256 levels is the 8-bit grey of a real thermal
 * display, and the modelled detectors are 320x240 and 640x480; the old
 * 16-band set was a texture-count convenience about fourteen times coarser
 * than the sensor resolves.
 *
 * The overlay reads QGVAR(selTemperature) (the same per-selection
 * physics state the thermal display writes) and the AGC window
 * (QGVAR(agcRadMin/Max)), so fusion and thermal agree on what is hot.
 * This function is called from the sensor tick while in NVG mode 1
 * with a fusion-capable headset.
 *
 * EDGE STATE AND THE BRIGHTNESS LADDER COMBINE, THEY DO NOT OVERWRITE.
 * Each selection gets one of the 256 emissive materials as its brightness
 * ladder.  A detected edge is a SEPARATE piece of state written to
 * QGVAR(selThermalEdge), keyed like the selection temperature, and it does
 * NOT touch the material slot.  The two are combined by keeping the ladder
 * on the material and carrying the edge alongside it: if the edge wrote to
 * the material slot, a detected edge would LOSE its correct thermal shading
 * to gain a marker.  The edge decision is LOCAL: the selection's band
 * radiance against the mean band radiance of the object's OTHER selections.
 * Any edge marker built from this state is a device CUE and not sensor
 * output.  No fielded dismounted thermal sight draws an automatic marker,
 * and detection on those devices is a human task, so no automatic cue is
 * drawn here.
 *
 * TRANSMISSION SCALES THE EDGE, AND THE WHOLE RANGE ENTERS THE BACKGROUND.
 * A selection's apparent radiance is its emitted and reflected terms
 * multiplied by the path transmission tau, plus the path radiance
 * (1 - tau) * W_atm.  A target and its local background lie at the SAME
 * range, so they share tau and the same path radiance.  In the DIFFERENCE
 * the path term cancels EXACTLY:
 *
 *     L_target - L_background = tau * (L_target0 - L_background0)
 *
 * The edge contrast is a ratio of that difference to the background
 * radiance, and the background radiance also carries the path term:
 *
 *     contrast = tau * (S0 - B0) / (tau * B0 + (1 - tau) * W_atm)
 *
 * The overlay therefore feeds the edge kernel the ATMOSPHERE-INCLUDED signal
 * and background.  That is the exact common-mode result.  Applying tau to
 * the target alone, or adding the path term to the target alone, is not
 * this result and is wrong.  The brightness ladder keeps the unattenuated
 * radiance, so the 256-band material slot does not move with range.
 *
 * SPATIAL RESOLUTION IS THE MISSING OTHER HALF.  A strong contrast edge is
 * NECESSARY AND NOT SUFFICIENT: a selection can stand above its local
 * background and still be smaller than the device can resolve.
 * FUNC(resolveThermalTarget) applies the Johnson criteria (STANAG 4347
 * Ed. 1) to the target's angular size, the device resolution and the optic
 * magnification, and the published edge state is the contrast decision AND
 * the resolvability verdict.  The fused headset is a UNITY goggle, so the
 * magnification on this path is 1: optics DEPENDS ON thermal, so calling its
 * optic table here would close a dependency cycle.  The kernel is general
 * and the 4x case is exercised in the test and the P71 probe.  No range and
 * no MRTD curve is invented.
 *
 * THE THERMAL CHANNEL HAS A FIELD, AND THE OVERLAY MUST RESPECT IT.  The
 * overlay had no angular limit of any kind: every object inside 300 m was
 * painted whatever direction it sat in.  The gate below refuses a target
 * whose angle from the VIEW CENTRE exceeds the thermal channel's half-angle.
 * THE BOUND IS DEFENSIBLE ON THE NUMBERS AND UNSUPPORTED BY THE PROSE: the
 * 34 against the intensified 40 makes the thermal geometrically NARROWER,
 * but both sources say OVERLAY and neither describes a bounded window, so
 * the gate is an inference from the figures and is labelled as one.
 *
 * THE AXIS IS DECLARED, NOT SOURCED, AND THE HEADER SAYS WHICH PART IS
 * WHICH.  No manufacturer datasheet in the image-intensifier family states
 * an axis for a field of view.  The Elbit AN/PVS-14 spec block reads
 * "Field of View - 40 nominal" beside "Objective Lens EFL 27 mm" with no
 * axis, and the L3Harris ENVG-B sheet reads "Flexible 40 Field-Of-View"
 * with no axis, so the family's 40 is pinned to no axis by any
 * manufacturer.  The one axis-bearing sheet in the family disclaims itself
 * on its own face: the L-3 Warrior Systems AN/PVS-31A sell sheet prints
 * "40 +/- 2 deg. (horizontal & vertical)" AND, on the same sheet, "This
 * document consists of basic marketing information that is not defined as
 * technical data".  A document that calls itself non-technical cannot be
 * the citation that pins an axis, so it is not used.  No horizontal or
 * vertical figure is published separately anywhere in the family, so the
 * aspect cannot be computed from real numbers either.  That is a clean
 * negative, and it is why the axis in the code is a DECLARATION.
 *
 * THE ONE PUBLISHED THERMAL-CHANNEL FIELD BELONGS TO THE BNVD-FUSED (F-BINO)
 * AND ITS INTENSIFIED SIDE IS THE SAME TUBE SET THIS CLASS RESOLVES TO.  TNVC
 * states a 12 um LWIR channel, a 34 diagonal field of view for the HUD and
 * AR display functions, overlayed onto the I2 image, in the right-side
 * optical pod, with modes "I2 Only, Fused + NAV, I2 + NAV, and I2 Standby".
 * Its intensified side is the PVS-31A tube set, and the in-game class
 * NVGogglesB_grn_F resolves to the PVS-31 tier on that same tube set, so
 * the figure is a FAIR source for this class and the DIAGONAL is the one
 * axis any source states.  The sourcing strength is DISTRIBUTOR-GRADE: TNVC
 * is a distributor and no manufacturer or Army corroboration was found, so
 * the log names the source strength and not a manufacturer.
 *
 * THE ENVG-B (AN/PSQ-42) HAS NO PUBLISHED THERMAL-CHANNEL FIGURE AT ALL.
 * L3Harris publishes ONE fused figure covering both channels.  That figure
 * is NOT split here, and the BNVD-FUSED's diagonal is NOT borrowed for it,
 * because they are different device families.  The ENVG-B therefore takes
 * the DECLARED DEFAULT and the log reads "declared" for it, so the absence
 * of published data is expressed in the code and visible in a log instead
 * of being hidden behind another device's number.
 *
 * THE GATE IS OBJECT SCALE, NOT PIXEL SCALE, AND THAT IS A LIMIT OF THE
 * RENDERER, NOT A CHOICE.  addons/ has no viewport, scissor, stencil or
 * render-target primitive, so the overlay's only pixel primitive is a
 * per-object setObjectMaterial, which is all-or-nothing per object.  A
 * building straddling the thermal half-angle is ENTIRELY one treatment or
 * the other and is never split, so the result is a soft, object-scale
 * field rather than a crisp rectangle.  No frame, border, outline or mask
 * is drawn to imply an optical edge the renderer cannot produce: a graphic
 * is not optics.  If the geometry looks too subtle to notice, that is the
 * honest reading and it is not compensated with art.
 *
 * Params:
 *   0: _player (OBJECT, default player)
 *
 * Returns: nothing.
 */
params [["_player", player, [objNull]], ["_mode", ""]];

// Restore the emissive materials.  This function swaps a material onto every
// thermal selection of every object within 300 m, and the selection set
// includes Man, so without a restore an operator who uses fusion and never
// enters thermal mode leaves fusion_emissive materials on world objects and
// on uniforms after returning to normal vision.  The sensor teardown calls
// this with EXIT.
if (_mode == "EXIT") exitWith {
    // Tear the field-of-view frame down first: the overlay is leaving NVG,
    // so the operator must not be left with a border over normal vision.
    [false] call FUNC(updateFusionFrame);
    // The outline overlay belongs to the same exit: clear it and lower its
    // display, or a stale outline survives into normal vision.
    [false] call FUNC(outlineToggle);
    // The solid fill owns a separate registry of textures.  Restore it here,
    // or a body stays a flat bright block after the operator leaves fusion.
    // The mode "EXIT" call does not need a live player.
    [_player, "EXIT"] call FUNC(applyFusionFill);
    private _restore = missionNamespace getVariable [QGVAR(fusionOverlaySaved), []];
    {
        _x params ["_o", "_oldMats"];
        if (!isNull _o) then {
            private _i = 0;
            {
                if (_i < count _oldMats && {(_oldMats select _i) isEqualType ""}) then {
                    _o setObjectMaterial [_i, _oldMats select _i];
                };
                _i = _i + 1;
            } forEach _oldMats;
        };
    } forEach _restore;
    missionNamespace setVariable [QGVAR(fusionOverlaySaved), []];
};

if (isNull _player) exitWith {};

// Wall-clock timer for this pass.  The overlay carried no timer, so the
// 17:58:27 RPT could not rank its cost against the other AEE work.  It is
// emitted once per pass at the end, through AEE_LOG_DEBUG.
private _perfT0 = diag_tickTime;

// Reuse the exact band quantisation from the thermal display: the AGC
// window and selection state are per-frame.
private _selMap = missionNamespace getVariable [QGVAR(selTemperature), createHashMap];
private _agcMin = missionNamespace getVariable [QGVAR(agcRadMin), -1];
private _agcMax = missionNamespace getVariable [QGVAR(agcRadMax), -1];
// The edge state is SEPARATE from the brightness ladder.  The 256 emissive
// materials are the brightness ladder and the material slot is theirs; an
// edge must not write to that slot, or the selection loses its thermal
// shading to gain a marker.  The ladder stays on the material and the edge is
// carried alongside it, keyed like the selection temperature.
private _edgeMap = missionNamespace getVariable [QGVAR(selThermalEdge), createHashMap];

// Resolve the mounted device and its SENSOR detection threshold ONCE per
// tick, not once per object.  The device is the same for every object.
// The background temperature for the threshold is the ambient air
// temperature the display already uses.  A dedicated server has no player,
// so the resolver is guarded the same way fnc_calculateThermalContrast
// does, and it falls back to the uncooled default the resolver itself
// returns for an unknown device.
private _tAir = missionNamespace getVariable [QEGVAR(core,currentTemperature), 15];
if !(_tAir isEqualType 0) then { _tAir = 15; };
// Atmospheric state for the path transmission, read ONCE per tick like the
// air temperature.  Rain is the engine scalar, not an AEE variable.
private _humidity = missionNamespace getVariable [QEGVAR(core,currentHumidity), 50];
if !(_humidity isEqualType 0) then { _humidity = 50; };
private _fog = missionNamespace getVariable [QEGVAR(core,currentFogDensity), 0];
if !(_fog isEqualType 0) then { _fog = 0; };
private _rain = rain;
if !(_rain isEqualType 0) then { _rain = 0; };
private _airDensity = missionNamespace getVariable [QEGVAR(core,currentAirDensity), 1.225];
if !(_airDensity isEqualType 0) then { _airDensity = 1.225; };
// The device pair is resolved ONCE per tick, before the object walk.  It
// carries the NVG tube row, the thermal channel row, the channel's
// half-angle and the provenance of that figure (declared, derived or
// published).  The thermal row's NETD and resolution drive the sensor
// threshold and the Johnson resolvability test below.
private _devicePair = [_player] call FUNC(resolveFusionDevice);
private _deviceRow = _devicePair select 1;
private _deviceNetd = _deviceRow param [0, 0.05];
private _deviceResX = _deviceRow param [1, 640];
private _thermalHalfAngleDeg = _devicePair select 2;
private _fovSource = _devicePair select 3;
private _fovAxis = _devicePair select 4;
private _thermalDevice = _devicePair select 5;
private _thermalDeviceId = _devicePair select 6;
if !(_deviceNetd isEqualType 0) then { _deviceNetd = 0.05; };
if (_deviceNetd <= 0) then { _deviceNetd = 0.05; };
if !(_deviceResX isEqualType 0) then { _deviceResX = 640; };
if (_deviceResX <= 0) then { _deviceResX = 640; };
// The detector band (T16): index 6 of the thermal row, default lwir.  A
// device that cannot be read keeps the LWIR default, so the no-device path
// reproduces the old LWIR result bit for bit.
private _band = _deviceRow param [6, "lwir"];
if !(_band isEqualType "") then { _band = "lwir"; };
private _bandEdges = [_band] call FUNC(resolveThermalBand);
private _lambda1M = _bandEdges select 0;
private _lambda2M = _bandEdges select 1;
// Sun elevation in degrees, published by the environmental solar model.
// The reflected-solar term is zero for LWIR and at night.
private _sunElev = missionNamespace getVariable [QEGVAR(core,currentSunElevation), -90];
if !(_sunElev isEqualType 0) then { _sunElev = -90; };
// Surface wetness drives the wet-emissivity blend at the selection point.
private _surfaceWetness = missionNamespace getVariable [QEGVAR(core,surfaceWetness), 0];
if !(_surfaceWetness isEqualType 0) then { _surfaceWetness = 0; };
// ─── The fusion field-of-view frame ────────────────────────────────────────
// A thin rectangular border at the thermal channel's half-angle, so the
// operator can see where the fused image is actually bounded.  It is a HUD
// aid, not optics.  The angle is the SAME _thermalHalfAngleDeg the gate uses,
// resolved by FUNC(resolveFusionDevice); the NVG device's own published field
// is the on-screen scale.  Nothing is drawn for a non-fusion device or with
// the setting off, and FUNC(updateFusionFrame) tears the display down when
// this call passes false.
private _nvgRow = _devicePair select 0;
private _nvgFieldDeg = _nvgRow param [5, 40];
if !(_nvgFieldDeg isEqualType 0) then { _nvgFieldDeg = 40; };
if (_nvgFieldDeg <= 0) then { _nvgFieldDeg = 40; };
private _frameOn = missionNamespace getVariable [QGVAR(fusionFovFrame), true];
if !(_frameOn isEqualType true) then { _frameOn = true; };
private _fusionDevice = (_thermalDevice == "ENVG-B") || (_thermalDevice == "BNVD-FUSED") || (_thermalDevice == "ECOTI");
[_frameOn && _fusionDevice, _thermalHalfAngleDeg, _nvgFieldDeg] call FUNC(updateFusionFrame);
// The fused headset is a UNITY-magnification goggle, so the optic
// magnification for THIS path is 1.  A magnified rifle-sight path would pass
// its optic magnification instead, but optics DEPENDS ON thermal (its
// fnc_getOpticProperties is a downstream consumer), so calling it here would
// close a dependency cycle.  The kernel takes magnification as a parameter
// and the test and the P71 probe exercise the 4x case.
private _mag = 1;
// The signal-to-noise multiple is an ENGINEERING CHOICE, not a standard:
// NETD is the signal-to-noise 1 point and reliable detection sits at 3 to
// 10 times that, and the record publishes no standard value.
private _snrMultiple = 5;
// The SENSOR detection threshold, derived per device.  It is NOT a display
// band step: the selection path steps 1/31 and this fusion ladder 1/255, so
// the two must not be conflated.  On this path the step is FINER than the
// sensor.  The band step stays a display concern in the ladder below.
private _sensorThreshold = [_deviceNetd, _snrMultiple, _tAir] call FUNC(calculateSensorThreshold);
if (_sensorThreshold <= 0) then { _sensorThreshold = 0.004349; };

// The 256-level emissive ladder.  The filenames are zero-padded to three
// digits, so the full path list is built ONCE and cached rather than
// formatted per selection per tick.  The band count changes only how many
// material FILES ship: the per-tick call count stays one setObjectMaterial
// per selection, exactly as with the old 16-band set.
private _mats = [] call FUNC(fusionMaterialPaths);

// ─── Diagnostic ───────────────────────────────────────────────────────────
// An overlay nobody can see in a log cannot be proved or refuted, which is
// the fault this replaces: the operator SAW the fusion overlay and the RPT
// carried no fusion line at all.  One batch per _LOG_INTERVAL names the
// decision this path made and the state it consumed.  Timed on diag_tickTime
// rather than a tick counter, and the FIRST tick logs unconditionally because
// -1e9 is already in the past.  The values are resolved once here and the
// line is emitted inside the planning forEach below, where the band and the
// selection count are in scope, so no hot path grows.
private _LOG_INTERVAL = 30;
private _logAt = missionNamespace getVariable [QGVAR(fusionLogAt), -1e9];
if !(_logAt isEqualType 0) then { _logAt = -1e9; };
private _logNow = diag_tickTime >= _logAt;
if (_logNow) then {
    missionNamespace setVariable [QGVAR(fusionLogAt), diag_tickTime + _LOG_INTERVAL];
};

// ─── Solid-fill display mode ──────────────────────────────────────────────
// QGVAR(fusionSolidFill) selects the solid texture fill from workshop
// 3810296503 fn_thermalFill IN PLACE OF the emissive ladder below, so one
// body is never painted by both primitives.  The display keeps one owner:
// this function drives the fill on its own tick, and the EXIT block above
// restores it.  The frame above is already driven, so it still tracks the
// channel.  A live switch from the ladder to the fill restores the ladder
// materials already on the world before handing over, or the body would
// carry both.
private _fillOn = missionNamespace getVariable [QGVAR(fusionSolidFill), false];
if !(_fillOn isEqualType true) then { _fillOn = false; };
if (_fillOn) exitWith {
    private _ladder = missionNamespace getVariable [QGVAR(fusionOverlaySaved), []];
    {
        _x params ["_o", "_oldMats"];
        if (!isNull _o) then {
            private _i = 0;
            {
                if ((_i < count _oldMats) && {(_oldMats select _i) isEqualType ""}) then {
                    _o setObjectMaterial [_i, _oldMats select _i];
                };
                _i = _i + 1;
            } forEach _oldMats;
        };
    } forEach _ladder;
    missionNamespace setVariable [QGVAR(fusionOverlaySaved), []];
    // The edge state is the ladder's companion.  With no ladder there is no
    // edge to publish, so clear it rather than leave a stale map for a
    // consumer to read.
    missionNamespace setVariable [QGVAR(selThermalEdge), createHashMap];
    [_player] call FUNC(applyFusionFill);
    if (_logNow) then {
        private _logFill = format [
            "fusion overlay: solid fill mode (dev=%1 tid=%2 halfDeg=%3)",
            _thermalDevice, _thermalDeviceId, _thermalHalfAngleDeg
        ];
        AEE_LOG_DEBUG(_logFill);
    };
};

// The setting can be turned off while the fill has bodies painted.  Restore
// them before the ladder takes the display back, or the solid texture and the
// emissive material would stack on the same body.  The registry is empty in
// the normal case, so this is one getVariable read on the ladder path.
if ((missionNamespace getVariable [QGVAR(fusionFillReg), []]) isNotEqualTo []) then {
    [_player, "EXIT"] call FUNC(applyFusionFill);
};
// ─── The thermal channel's field ──────────────────────────────────────────
// The half-angle and its provenance are resolved with the device pair at the
// top of this function.  FUNC(resolveFusionDevice) reads the corpus thermal
// row through the generated matcher and labels the figure.  The long
// sourcing note for each device lives in fnc_resolveFusionDevice.sqf and
// fnc_fusionThermalField.sqf.

// The view axis, sampled ONCE per tick rather than once per object.  The
// per-frame handler already walks the whole object list, so a value that is
// identical for every object in the tick belongs outside the loop: a
// per-object camera read would grow the hot path for a value that cannot
// differ between objects.  EFUNC(core,getEyeState) is the repository's
// existing cached eye-state call, used by fnc_applyThermalVision and by
// fnc_applyNVGTubeModel, and it returns the camera look vector in every
// state including a turret and freelook, so the gate agrees with the tube
// model on where the operator is looking.  getCameraViewDirection is
// verified present in the dedicated-server binary and is the alternative,
// but naming it here would add a second look path that no other AEE caller
// uses.  The vector is guarded on shape and falls back to the unit's own
// facing, which is the same fallback getEyeState applies.
private _eyeState = [_player] call EFUNC(core,getEyeState);
private _eye = _eyeState select 0;
private _viewDir = _eyeState select 1;
if !(_viewDir isEqualType [] && {count _viewDir == 3}) then { _viewDir = vectorDir _player; };

private _visionMode = currentVisionMode _player;
private _capable = [] call EFUNC(thermal,isFusionCapable);
private _fusionMode = missionNamespace getVariable [QGVAR(fusionMode), 0];
// ─── Bounded candidate sweep ──────────────────────────────────────────────
// The previous line ran `_player nearObjects 300` on EVERY fusion tick at
// 10 Hz and then planned every returned object, so a 232-object candidate set
// cost a full per-selection solve on every pass.  Discovery is now CACHED and
// the plan is BOUNDED, the same shape fnc_applyBuildingThermal uses: the
// candidate list refreshes on a 1 s timer and each pass takes at most
// `sweepBudget` objects from a persistent pending queue.  A newly seen object
// enters within about one second, and the queue drains at 16 objects per
// pass.  `_objectCount` stays the whole candidate set, not the batch, so the
// `objs=` gate field keeps its meaning.
private _sweepBudget = missionNamespace getVariable [QGVAR(sweepBudget), 16];
if !(_sweepBudget isEqualType 0) then { _sweepBudget = 16; };
private _pending = missionNamespace getVariable [QGVAR(fusionPending), []];
if !(_pending isEqualType []) then { _pending = []; };
private _candT = missionNamespace getVariable [QGVAR(fusionCandidatesT), -99];
if !(_candT isEqualType 0) then { _candT = -99; };
if ((_pending isEqualTo []) || ((diag_tickTime - _candT) > 1)) then {
    _pending = _player nearObjects 300;
    missionNamespace setVariable [QGVAR(fusionCandidatesT), diag_tickTime];
    missionNamespace setVariable [QGVAR(fusionCandidatesCount), count _pending];
};
private _objectCount = missionNamespace getVariable [QGVAR(fusionCandidatesCount), count _pending];
if !(_objectCount isEqualType 0) then { _objectCount = count _pending; };
private _taken = [_pending, _sweepBudget] call FUNC(takeThermalSweep);
private _objects = _taken select 0;
missionNamespace setVariable [QGVAR(fusionPending), _taken select 1];
// Gate tallies for the diagnostic.  A gate whose effect cannot be read in a
// log is a gate nobody can check next session, and that has been the failure
// mode in this area more than once, so the rejected and the painted counts
// are accumulated here and reported below.
private _gatedOut = 0;
private _paintedCount = 0;
{
    private _obj = _x;
    // A cached queue can outlive an object; a fresh nearObjects list could
    // not.  Skip a deleted object before any engine call touches it.
    if (isNull _obj) then { continue; };
    private _objMaxBand = 0;
    // Shared dynamic discovery (issue #204): Man = all texture slots,
    // vehicle = config override > textureSources > all-but-MFD.  The
    // single source of truth so fusion and thermal agree on every part.
    private _selIdxs = [_obj] call FUNC(getThermalSelections);
    private _hs = getArray (configOf _obj >> "hiddenSelections");

    // The path transmission for this object's range.  Range is the distance
    // from the player, which the overlay already has.  Every selection of ONE
    // object shares the range, so tau is resolved once per object, not once
    // per selection.  A refused kernel result (-1) falls back to no
    // attenuation so a bad input cannot black out the edge.
    private _range = _player distance _obj;
    private _tau = [_range, _humidity, _tAir, _fog, _rain, _airDensity, _band] call FUNC(calculateAtmosphericTransmission);
    if !(_tau isEqualType 0) then { _tau = 1; };
    if (_tau < 0) then { _tau = 1; };
    if !(finite _tau) then { _tau = 1; };

    // Target critical dimension: the SMALLEST extent of the object's
    // bounding box is the dimension Johnson's criteria resolve.  Every
    // selection of one object inherits it, and all of them share the range,
    // so the angular size is resolved once per object, not per selection.
    // A degenerate box gives a zero angle and the kernel then reports the
    // target unresolved, which is the safe reading of "no geometry".
    private _bb = boundingBoxReal _obj;
    private _dim = (((_bb select 1) select 0) - ((_bb select 0) select 0))
        min (((_bb select 1) select 1) - ((_bb select 0) select 1))
        min (((_bb select 1) select 2) - ((_bb select 0) select 2));
    private _targetAngleRad = (_dim max 0) / (_range max 0.1);

    // ── The offset gate ────────────────────────────────────────────────────
    // A target whose bearing from the view axis exceeds the thermal channel's
    // half-angle is outside the fused image, so it receives no emissive
    // material and keeps its own.  acos is the correct command here and NOT
    // acosDeg: strings on the dedicated-server binary carry acos and do NOT
    // carry acosDeg, and a bare absent token is a parse error that aborts
    // the whole file at preInit because XEH_PREP compiles every function on
    // every machine.  The dot product is clamped to [-1, 1] because a
    // normalised pair can exceed 1 by rounding, and acos of a value above 1
    // is NaN, which would make every comparison false and silently paint
    // the whole screen again.  The vector commands used here
    // (vectorDotProduct, vectorNormalized, vectorMagnitude) are all verified
    // present in that same binary.
    private _insideField = [_eye, _viewDir, getPosASLVisual _obj, _thermalHalfAngleDeg] call FUNC(fusionFovGate);
    if (!_insideField) then {
        _gatedOut = _gatedOut + 1;
        // A target that WAS inside the field and is now outside it still
        // carries the emissive material it was given on an earlier tick,
        // because the swap is per-object and nothing else clears it.  Its
        // own materials are restored here and its entry is dropped, or the
        // gate would freeze a heat map wherever the operator last looked,
        // which is the same fault the gate replaces.  An object that was
        // never painted has no entry, so this is a no-op for it.
        private _saved = missionNamespace getVariable [QGVAR(fusionOverlaySaved), []];
        private _slot = _saved findIf { (_x select 0) == _obj };
        if (_slot >= 0) then {
            private _oldMats = (_saved select _slot) select 1;
            private _ri = 0;
            {
                if ((_ri < count _oldMats) && {(_oldMats select _ri) isEqualType ""}) then {
                    _obj setObjectMaterial [_ri, _oldMats select _ri];
                };
                _ri = _ri + 1;
            } forEach _oldMats;
            _saved deleteAt _slot;
            missionNamespace setVariable [QGVAR(fusionOverlaySaved), _saved];
        };
        continue;
    };
    _paintedCount = _paintedCount + 1;

    // Save the object's own materials ONCE per session, before the first
    // swap.  Saving every tick would capture the already-swapped emissive
    // material, and the EXIT restore would then put the emissive material
    // back instead of the object's own.
    if (_selIdxs isNotEqualTo []) then {
        private _restore = missionNamespace getVariable [QGVAR(fusionOverlaySaved), []];
        if ((_restore findIf { (_x select 0) == _obj }) < 0) then {
            _restore pushBack [_obj, getObjectMaterials _obj];
            missionNamespace setVariable [QGVAR(fusionOverlaySaved), _restore];
        };
    };

    // Pass 1: solve every selection's band radiance once, so pass 2 can use
    // the object's OTHER selections as its local background.
    private _solved = [];
    {
        private _idx = _x;
        private _selName = if (_obj isKindOf "Man") then {
            private _names = selectionNames _obj;
            if (_idx < count _names) then { _names select _idx } else { "" }
        } else {
            if (_idx < count _hs) then { _hs select _idx } else { "" }
        };
        if (_selName == "") then { continue; };
        private _stateKey = format ["%1|%2", _obj, _selName];
        private _tNew = _selMap getOrDefault [_stateKey, -999];
        if (_tNew <= -900) then { continue; };
        private _mat = ([_obj, _selName] call FUNC(getSelectionMaterials)) call FUNC(getMaterialThermal);
        private _eps = _mat select 0;
        // A rain-wetted surface emits toward the liquid-water value (T9).
        _eps = [_eps, _surfaceWetness] call FUNC(getEffectiveEmissivity);
        // Reflected-solar band radiance (T4): zero for LWIR and at night.
        private _wSolar = [_band, _eps, _sunElev] call FUNC(calculateReflectedSolarBand);
        // The ambient background temperature is resolved once per tick
        // above the object loop, and it drives the radiance and the
        // sensor threshold alike.
        // Ground radiance coefficient: the thermal display passes 0.5 as
        // the default ground-term proxy (fnc_applySelectionThermal
        // param 4).  Keep the same value so fusion and thermal agree.
        private _fGround = 0.5;
        // Brightness-ladder radiance: no atmosphere, so the 256-band material
        // slot does not move with range.  This is the DISPLAY quantity.
        private _rad = [_tNew, _eps, _tAir, _fGround, _tNew, 1, 15, true, _lambda1M, _lambda2M, _humidity, _band, _wSolar] call FUNC(calculateBandRadiance);
        // Edge radiance: the SAME selection seen through the path, so the
        // emitted and reflected terms carry tau and the path term is added.
        // The target and its local background share the range, so they share
        // tau and the same W_atm, and the difference carries tau alone.
        private _edgeRad = [_tNew, _eps, _tAir, _fGround, _tNew, _tau, _tAir, true, _lambda1M, _lambda2M, _humidity, _band, _wSolar] call FUNC(calculateBandRadiance);
        if (!(_agcMin isEqualType 0) || !(_agcMax isEqualType 0) || _agcMin >= _agcMax) then {
            _agcMin = [-40, _eps, _tAir, _fGround, _tNew, 1, 15, true, _lambda1M, _lambda2M, _humidity, _band, _wSolar] call FUNC(calculateBandRadiance);
            _agcMax = [150, _eps, _tAir, _fGround, _tNew, 1, 15, true, _lambda1M, _lambda2M, _humidity, _band, _wSolar] call FUNC(calculateBandRadiance);
        };
        _solved pushBack [_idx, _stateKey, _rad, _edgeRad];
    } forEach _selIdxs;

    // Pass 2: local-background edge test, then the brightness ladder.  The
    // background is the mean band radiance of the object's OTHER selections.
    // A single-selection object has no other selection, so its background is
    // 0 and the kernel refuses it: no local background, no edge.
    private _n = count _solved;
    for "_i" from 0 to (_n - 1) do {
        private _entryIdx = (_solved select _i) select 0;
        private _entryKey = (_solved select _i) select 1;
        // The DISPLAY radiance (no atmosphere) drives the brightness ladder,
        // and the ATMOSPHERE-INCLUDED radiance drives the edge.  They are
        // separate, so the 256-band material slot does not move with range.
        private _entryBright = (_solved select _i) select 2;
        private _entryRad = (_solved select _i) select 3;
        private _bgSum = 0;
        private _bgCount = 0;
        for "_j" from 0 to (_n - 1) do {
            if (_j != _i) then {
                private _other = _solved select _j;
                // The local background carries the SAME tau and the SAME path
                // term as the target, because they share the range.
                _bgSum = _bgSum + (_other select 3);
                _bgCount = _bgCount + 1;
            };
        };
        private _localBg = if (_bgCount > 0) then { _bgSum / _bgCount } else { 0 };
        private _edgeResult = [_entryRad, _localBg, _sensorThreshold] call FUNC(evaluateThermalEdge);
        // SPATIAL RESOLUTION: a CONTRAST edge is necessary and NOT
        // sufficient.  A selection can stand above its local background and
        // still be smaller than the device resolves, so the published edge
        // state is the contrast decision AND the Johnson-criteria verdict.
        // The kernel decides geometry only; it invents no range.
        private _spatial = [_targetAngleRad, _deviceResX, _mag] call FUNC(resolveThermalTarget);
        private _resolvable = _spatial select 0;
        _edgeMap set [_entryKey, (_edgeResult select 0) && _resolvable];
        private _b = ((_entryBright - _agcMin) / ((_agcMax - _agcMin) max 1e-6)) max 0 min 1;
        if !(finite _b) then { _b = 0; };
        // 256-level display quantiser.  A real thermal display is 8-bit grey
        // and the modelled detectors are 320x240 and 640x480.  The old
        // 16-band step (1/16 = 0.0625) was a texture-count convenience about
        // fourteen times coarser than the sensor resolves.
        private _band = [_b] call FUNC(fusionBandIndex);
        private _matPath = _mats select _band;
        _obj setObjectMaterial [_entryIdx, _matPath];
        _objMaxBand = _objMaxBand max _band;
    };

    // The diagnostic, emitted where the band and the selection count are
    // already in scope so no hot path grows.  One line per object per
    // window: the vision mode and the capability decision the dispatcher
    // made, the mode that was actually applied, this object's selection
    // count and the brightest band the renderer wrote for it.
    if (_logNow) then {
        private _logMsg = format [
            "fusion overlay: vm=%1 capable=%2 mode=%3 objs=%4 obj=%5 sels=%6 maxBand=%7",
            _visionMode, _capable, _fusionMode, _objectCount, typeOf _obj, _n, _objMaxBand
        ];
        AEE_LOG_DEBUG(_logMsg);
    };
} forEach _objects;

// The GATE line, emitted once per window after the loop, because the
// rejected and painted counts are only final there.  It names the device the
// field was taken from, the half-angle in use, whether that value is derived
// from a source or declared here, and how many candidates the offset gate
// turned away.  "fov=declared" in this line is the record that a device with
// no published thermal field is running on a declared default, and a gate
// that cannot be read in a log is a gate nobody can check next session.
if (_logNow) then {
    private _corpusState = ["live", "data-only"] select (_thermalDeviceId == "");
    private _logGate = format [
        "fusion gate: dev=%1 tid=%2 corpus=%3 fov=%4 axis=%5 halfDeg=%6 objs=%7 gated=%8 painted=%9 batch=%10 pending=%11",
        _thermalDevice, _thermalDeviceId, _corpusState, _fovSource, _fovAxis,
        _thermalHalfAngleDeg, _objectCount, _gatedOut, _paintedCount,
        count _objects, count (_taken select 1)
    ];
    AEE_LOG_DEBUG(_logGate);
};

// Publish the edge state for the tick.  It is separate from the brightness
// ladder, so an edge can never overwrite a selection's thermal shading.
missionNamespace setVariable [QGVAR(selThermalEdge), _edgeMap];

// Per-pass wall clock, built only when the debug switch is on (AEE_TRACE_ON)
// and emitted through AEE_LOG_DEBUG.  This is the line the overlay lacked, and
// it names the batch and the pending remainder so the bounded sweep can be
// read straight from a performance run.
if (AEE_TRACE_ON) then {
    private _perfMsg = format [
        "fusion overlay %1 ms (batch %2, pending %3, candidates %4)",
        round ((diag_tickTime - _perfT0) * 1000),
        count _objects, count (_taken select 1), _objectCount
    ];
    AEE_LOG_DEBUG(_perfMsg);
};
