#include "..\..\script_component.hpp"
/*
 * Fusion overlay (issue #204, Track B ENVG-B).
 *
 * Renders the physics-driven thermal state as an emissive overlay on
 * top of the NVG base view.  Real fusion goggles (L3Harris ENVG-B,
 * AN/PSQ-20) blend an image-intensified I2 tube image with a thermal
 * microbolometer image; the thermal channel is a separate composited
 * source, not the native TI mode.
 *
 * Mechanism (proven by the workshop audit - A3TI EmissiveWhite.rvmat,
 * workshop 2041057379): swap each object's thermal selections to an
 * rvmat whose EMISSIVE carries the heat.  A3TI uses a binary
 * full-white (emmisive 500, AlwaysInShadow, ambient 20) so everything
 * glows white over the NVG.  We grade it by the SAME physics + AGC
 * state as the thermal display: hotter selections glow brighter,
 * cooler selections stay dark.  The 256 generated fusion_emissive_NNN
 * rvmats carry emissive = band_grey * 500 (band_255 = full A3TI white), so
 * band_128 glows about half as bright.  The ladder is generated by
 * tools/gen_fusion_emissive_materials.py, so the count is auditable and the
 * set is reproducible.  256 levels is the 8-bit grey of a real thermal
 * display, and the modelled detectors are 320x240 and 640x480; the old
 * 16-band set was a texture-count convenience about fourteen times coarser
 * than the sensor resolves.
 *
 * The overlay reads QGVAR(selTemperature) (the same per-selection
 * physics state the thermal display writes) and the AGC window
 * (QGVAR(agcRadMin/Max)), so fusion and thermal agree on what is hot.
 * This function is called from the sensor tick while in NVG mode 1
 * with a fusion-capable headset.
 *
 * EDGE STATE AND THE BRIGHTNESS LADDER COMBINE, THEY DO NOT OVERWRITE.
 * Each selection gets one of the 256 emissive materials as its brightness
 * ladder.  A detected edge is a SEPARATE piece of state written to
 * QGVAR(selThermalEdge), keyed like the selection temperature, and it does
 * NOT touch the material slot.  The two are combined by keeping the ladder
 * on the material and carrying the edge alongside it: if the edge wrote to
 * the material slot, a detected edge would LOSE its correct thermal shading
 * to gain a marker.  The edge decision is LOCAL: the selection's band
 * radiance against the mean band radiance of the object's OTHER selections.
 * Any edge marker built from this state is a device CUE and not sensor
 * output.  No fielded dismounted thermal sight draws an automatic marker,
 * and detection on those devices is a human task, so no automatic cue is
 * drawn here.
 *
 * TRANSMISSION SCALES THE EDGE, AND THE WHOLE RANGE ENTERS THE BACKGROUND.
 * A selection's apparent radiance is its emitted and reflected terms
 * multiplied by the path transmission tau, plus the path radiance
 * (1 - tau) * W_atm.  A target and its local background lie at the SAME
 * range, so they share tau and the same path radiance.  In the DIFFERENCE
 * the path term cancels EXACTLY:
 *
 *     L_target - L_background = tau * (L_target0 - L_background0)
 *
 * The edge contrast is a ratio of that difference to the background
 * radiance, and the background radiance also carries the path term:
 *
 *     contrast = tau * (S0 - B0) / (tau * B0 + (1 - tau) * W_atm)
 *
 * The overlay therefore feeds the edge kernel the ATMOSPHERE-INCLUDED signal
 * and background.  That is the exact common-mode result.  Applying tau to
 * the target alone, or adding the path term to the target alone, is not
 * this result and is wrong.  The brightness ladder keeps the unattenuated
 * radiance, so the 256-band material slot does not move with range.
 *
 * SPATIAL RESOLUTION IS THE MISSING OTHER HALF.  A strong contrast edge is
 * NECESSARY AND NOT SUFFICIENT: a selection can stand above its local
 * background and still be smaller than the device can resolve.
 * FUNC(resolveThermalTarget) applies the Johnson criteria (STANAG 4347
 * Ed. 1) to the target's angular size, the device resolution and the optic
 * magnification, and the published edge state is the contrast decision AND
 * the resolvability verdict.  The fused headset is a UNITY goggle, so the
 * magnification on this path is 1: optics DEPENDS ON thermal, so calling its
 * optic table here would close a dependency cycle.  The kernel is general
 * and the 4x case is exercised in the test and the P71 probe.  No range and
 * no MRTD curve is invented.
 *
 * Params:
 *   0: _player (OBJECT, default player)
 *
 * Returns: nothing.
 */
params [["_player", player, [objNull]], ["_mode", ""]];

// Restore the emissive materials.  This function swaps a material onto every
// thermal selection of every object within 300 m, and the selection set
// includes Man, so without a restore an operator who uses fusion and never
// enters thermal mode leaves fusion_emissive materials on world objects and
// on uniforms after returning to normal vision.  The sensor teardown calls
// this with EXIT.
if (_mode == "EXIT") exitWith {
    private _restore = missionNamespace getVariable [QGVAR(fusionOverlaySaved), []];
    {
        _x params ["_o", "_oldMats"];
        if (!isNull _o) then {
            private _i = 0;
            {
                if (_i < count _oldMats && {(_oldMats select _i) isEqualType ""}) then {
                    _o setObjectMaterial [_i, _oldMats select _i];
                };
                _i = _i + 1;
            } forEach _oldMats;
        };
    } forEach _restore;
    missionNamespace setVariable [QGVAR(fusionOverlaySaved), []];
};

if (isNull _player) exitWith {};

// Reuse the exact band quantisation from the thermal display: the AGC
// window and selection state are per-frame.
private _selMap = missionNamespace getVariable [QGVAR(selTemperature), createHashMap];
private _agcMin = missionNamespace getVariable [QGVAR(agcRadMin), -1];
private _agcMax = missionNamespace getVariable [QGVAR(agcRadMax), -1];
// The edge state is SEPARATE from the brightness ladder.  The 256 emissive
// materials are the brightness ladder and the material slot is theirs; an
// edge must not write to that slot, or the selection loses its thermal
// shading to gain a marker.  The ladder stays on the material and the edge is
// carried alongside it, keyed like the selection temperature.
private _edgeMap = missionNamespace getVariable [QGVAR(selThermalEdge), createHashMap];

// Resolve the mounted device and its SENSOR detection threshold ONCE per
// tick, not once per object.  The device is the same for every object.
// The background temperature for the threshold is the ambient air
// temperature the display already uses.  A dedicated server has no player,
// so the resolver is guarded the same way fnc_calculateThermalContrast
// does, and it falls back to the uncooled default the resolver itself
// returns for an unknown device.
private _tAir = missionNamespace getVariable [QEGVAR(core,currentTemperature), 15];
if !(_tAir isEqualType 0) then { _tAir = 15; };
// Atmospheric state for the path transmission, read ONCE per tick like the
// air temperature.  Rain is the engine scalar, not an AEE variable.
private _humidity = missionNamespace getVariable [QEGVAR(core,currentHumidity), 50];
if !(_humidity isEqualType 0) then { _humidity = 50; };
private _fog = missionNamespace getVariable [QEGVAR(core,currentFogDensity), 0];
if !(_fog isEqualType 0) then { _fog = 0; };
private _rain = rain;
if !(_rain isEqualType 0) then { _rain = 0; };
private _airDensity = missionNamespace getVariable [QEGVAR(core,currentAirDensity), 1.225];
if !(_airDensity isEqualType 0) then { _airDensity = 1.225; };
private _deviceNetd = 0.05;
private _deviceResX = 640;
if (!isNull _player) then {
    private _dev = [_player, (vehicle _player)] call EFUNC(thermal,getThermalDeviceProperties);
    _deviceNetd = _dev param [0, 0.05];
    _deviceResX = _dev param [1, 640];
};
if !(_deviceNetd isEqualType 0) then { _deviceNetd = 0.05; };
if (_deviceNetd <= 0) then { _deviceNetd = 0.05; };
if !(_deviceResX isEqualType 0) then { _deviceResX = 640; };
if (_deviceResX <= 0) then { _deviceResX = 640; };
// The fused headset is a UNITY-magnification goggle, so the optic
// magnification for THIS path is 1.  A magnified rifle-sight path would pass
// its optic magnification instead, but optics DEPENDS ON thermal (its
// fnc_getOpticProperties is a downstream consumer), so calling it here would
// close a dependency cycle.  The kernel takes magnification as a parameter
// and the test and the P71 probe exercise the 4x case.
private _mag = 1;
// The signal-to-noise multiple is an ENGINEERING CHOICE, not a standard:
// NETD is the signal-to-noise 1 point and reliable detection sits at 3 to
// 10 times that, and the record publishes no standard value.
private _snrMultiple = 5;
// The SENSOR detection threshold, derived per device.  It is NOT a display
// band step: the selection path steps 1/31 and this fusion ladder 1/255, so
// the two must not be conflated.  On this path the step is FINER than the
// sensor.  The band step stays a display concern in the ladder below.
private _sensorThreshold = [_deviceNetd, _snrMultiple, _tAir] call FUNC(calculateSensorThreshold);
if (_sensorThreshold <= 0) then { _sensorThreshold = 0.004349; };

// The 256-level emissive ladder.  The filenames are zero-padded to three
// digits, so the full path list is built ONCE and cached rather than
// formatted per selection per tick.  The band count changes only how many
// material FILES ship: the per-tick call count stays one setObjectMaterial
// per selection, exactly as with the old 16-band set.
private _mats = missionNamespace getVariable [QGVAR(fusionEmissiveMats), []];
if (_mats isEqualTo []) then {
    _mats = [];
    for "_mi" from 0 to 255 do {
        private _mn = str _mi;
        while { count _mn < 3 } do { _mn = "0" + _mn; };
        _mats pushBack format [QPATHTOF(data\fusion_emissive_%1.rvmat), _mn];
    };
    missionNamespace setVariable [QGVAR(fusionEmissiveMats), _mats];
};

private _objects = _player nearObjects 300;
{
    private _obj = _x;
    // Shared dynamic discovery (issue #204): Man = all texture slots,
    // vehicle = config override > textureSources > all-but-MFD.  The
    // single source of truth so fusion and thermal agree on every part.
    private _selIdxs = [_obj] call FUNC(getThermalSelections);
    private _hs = getArray (configOf _obj >> "hiddenSelections");

    // The path transmission for this object's range.  Range is the distance
    // from the player, which the overlay already has.  Every selection of ONE
    // object shares the range, so tau is resolved once per object, not once
    // per selection.  A refused kernel result (-1) falls back to no
    // attenuation so a bad input cannot black out the edge.
    private _range = _player distance _obj;
    private _tau = [_range, _humidity, _tAir, _fog, _rain, _airDensity] call FUNC(calculateAtmosphericTransmission);
    if !(_tau isEqualType 0) then { _tau = 1; };
    if (_tau < 0) then { _tau = 1; };
    if !(finite _tau) then { _tau = 1; };

    // Target critical dimension: the SMALLEST extent of the object's
    // bounding box is the dimension Johnson's criteria resolve.  Every
    // selection of one object inherits it, and all of them share the range,
    // so the angular size is resolved once per object, not per selection.
    // A degenerate box gives a zero angle and the kernel then reports the
    // target unresolved, which is the safe reading of "no geometry".
    private _bb = boundingBoxReal _obj;
    private _dim = (((_bb select 1) select 0) - ((_bb select 0) select 0))
        min (((_bb select 1) select 1) - ((_bb select 0) select 1))
        min (((_bb select 1) select 2) - ((_bb select 0) select 2));
    private _targetAngleRad = (_dim max 0) / (_range max 0.1);

    // Save the object's own materials ONCE per session, before the first
    // swap.  Saving every tick would capture the already-swapped emissive
    // material, and the EXIT restore would then put the emissive material
    // back instead of the object's own.
    if (_selIdxs isNotEqualTo []) then {
        private _restore = missionNamespace getVariable [QGVAR(fusionOverlaySaved), []];
        if ((_restore findIf { (_x select 0) == _obj }) < 0) then {
            _restore pushBack [_obj, getObjectMaterials _obj];
            missionNamespace setVariable [QGVAR(fusionOverlaySaved), _restore];
        };
    };

    // Pass 1: solve every selection's band radiance once, so pass 2 can use
    // the object's OTHER selections as its local background.
    private _solved = [];
    {
        private _idx = _x;
        private _selName = if (_obj isKindOf "Man") then {
            private _names = selectionNames _obj;
            if (_idx < count _names) then { _names select _idx } else { "" }
        } else {
            if (_idx < count _hs) then { _hs select _idx } else { "" }
        };
        if (_selName == "") then { continue; };
        private _stateKey = format ["%1|%2", _obj, _selName];
        private _tNew = _selMap getOrDefault [_stateKey, -999];
        if (_tNew <= -900) then { continue; };
        private _mat = ([_obj, _selName] call FUNC(getSelectionMaterials)) call FUNC(getMaterialThermal);
        private _eps = _mat select 0;
        // The ambient background temperature is resolved once per tick
        // above the object loop, and it drives the radiance and the
        // sensor threshold alike.
        // Ground radiance coefficient: the thermal display passes 0.5 as
        // the default ground-term proxy (fnc_applySelectionThermal
        // param 4).  Keep the same value so fusion and thermal agree.
        private _fGround = 0.5;
        // Brightness-ladder radiance: no atmosphere, so the 256-band material
        // slot does not move with range.  This is the DISPLAY quantity.
        private _rad = [_tNew, _eps, _tAir, _fGround, _tNew] call FUNC(calculateBandRadiance);
        // Edge radiance: the SAME selection seen through the path, so the
        // emitted and reflected terms carry tau and the path term is added.
        // The target and its local background share the range, so they share
        // tau and the same W_atm, and the difference carries tau alone.
        private _edgeRad = [_tNew, _eps, _tAir, _fGround, _tNew, _tau, _tAir] call FUNC(calculateBandRadiance);
        if (!(_agcMin isEqualType 0) || !(_agcMax isEqualType 0) || _agcMin >= _agcMax) then {
            _agcMin = [-40, _eps, _tAir, _fGround, _tNew] call FUNC(calculateBandRadiance);
            _agcMax = [150, _eps, _tAir, _fGround, _tNew] call FUNC(calculateBandRadiance);
        };
        _solved pushBack [_idx, _stateKey, _rad, _edgeRad];
    } forEach _selIdxs;

    // Pass 2: local-background edge test, then the brightness ladder.  The
    // background is the mean band radiance of the object's OTHER selections.
    // A single-selection object has no other selection, so its background is
    // 0 and the kernel refuses it: no local background, no edge.
    private _n = count _solved;
    for "_i" from 0 to (_n - 1) do {
        private _entryIdx = (_solved select _i) select 0;
        private _entryKey = (_solved select _i) select 1;
        // The DISPLAY radiance (no atmosphere) drives the brightness ladder,
        // and the ATMOSPHERE-INCLUDED radiance drives the edge.  They are
        // separate, so the 256-band material slot does not move with range.
        private _entryBright = (_solved select _i) select 2;
        private _entryRad = (_solved select _i) select 3;
        private _bgSum = 0;
        private _bgCount = 0;
        for "_j" from 0 to (_n - 1) do {
            if (_j != _i) then {
                private _other = _solved select _j;
                // The local background carries the SAME tau and the SAME path
                // term as the target, because they share the range.
                _bgSum = _bgSum + (_other select 3);
                _bgCount = _bgCount + 1;
            };
        };
        private _localBg = if (_bgCount > 0) then { _bgSum / _bgCount } else { 0 };
        private _edgeResult = [_entryRad, _localBg, _sensorThreshold] call FUNC(evaluateThermalEdge);
        // SPATIAL RESOLUTION: a CONTRAST edge is necessary and NOT
        // sufficient.  A selection can stand above its local background and
        // still be smaller than the device resolves, so the published edge
        // state is the contrast decision AND the Johnson-criteria verdict.
        // The kernel decides geometry only; it invents no range.
        private _spatial = [_targetAngleRad, _deviceResX, _mag] call FUNC(resolveThermalTarget);
        private _resolvable = _spatial select 0;
        _edgeMap set [_entryKey, (_edgeResult select 0) && _resolvable];
        private _b = ((_entryBright - _agcMin) / ((_agcMax - _agcMin) max 1e-6)) max 0 min 1;
        if !(finite _b) then { _b = 0; };
        // 256-level display quantiser.  A real thermal display is 8-bit grey
        // and the modelled detectors are 320x240 and 640x480.  The old
        // 16-band step (1/16 = 0.0625) was a texture-count convenience about
        // fourteen times coarser than the sensor resolves.
        private _band = round (_b * 255) min 255 max 0;
        private _matPath = _mats select _band;
        _obj setObjectMaterial [_entryIdx, _matPath];
    };
} forEach _objects;

// Publish the edge state for the tick.  It is separate from the brightness
// ladder, so an edge can never overwrite a selection's thermal shading.
missionNamespace setVariable [QGVAR(selThermalEdge), _edgeMap];
