/*
fnc_devDumpAll - call every module state dump in one pass.

The list below is the State dump column of the debug index annex
(docs/wiki/annexes/annex-d-debug-index.qmd, generated by
tools/validation/gen_debug_index.py). tools/tests/test_dev_workbench.py
parses the annex and fails when this list drifts from it, so a module the
annex gains or loses is caught there.

Each dump is resolved at runtime and called with no arguments. A dump that
returns nothing still logs its own state line. A name with no live function
is REPORTED as an error line, not silently skipped.

This reuses the existing dump functions only: it defines no new state and no
second monitor.

Arguments: none.
Return Value: ARRAY - one line per dump (or one error line per missing dump).
*/

private _dumps = [
    "aee_actions_fnc_dumpState",
    "aee_ai_fnc_dumpState",
    "aee_armour_fnc_dumpState",
    "aee_atmos_fnc_dumpState",
    "aee_ballistics_fnc_dumpState",
    "aee_compat_ace3_fnc_dumpState",
    "aee_compat_realweather_fnc_dumpState",
    "aee_diagnostics_fnc_dumpPerformanceCounters",
    "aee_diagnostics_fnc_dumpState",
    "aee_lighting_fnc_logSkyState",
    "aee_particles_fnc_dumpState",
    "aee_maritime_fnc_dumpState",
    "aee_material_fnc_dumpState",
    "aee_flight_fnc_logAirframeState",
    "aee_flight_fnc_logFixedWingState",
    "aee_nightvision_fnc_dumpState",
    "aee_optics_fnc_dumpState",
    "aee_physiology_fnc_dumpState",
    "aee_radio_fnc_dumpState",
    "aee_thermal_fnc_dumpState",
    "aee_wildlife_fnc_logWildlifeState"
];

private _out = [];
{
    private _fnc = missionNamespace getVariable [_x, nil];
    if (isNil "_fnc" || { (typeName _fnc) != "CODE" }) then {
        _out pushBack format ["error: no dump for %1", _x];
    } else {
        private _result = [] call _fnc;
        _out pushBack (if (isNil "_result") then {
            format ["%1: state line emitted", _x]
        } else {
            format ["%1: %2", str _x, str _result]
        });
    };
} forEach _dumps;

_out
