PREP(calculateWBGT);
PREP(calculateHeatIndex);
PREP(calculateHypothermiaRisk);
PREP(calculateFreezingRain);
PREP(calculateWaterTemperature);
PREP(calculateThermalCrossover);
PREP(calculateObjectTemperature);
PREP(calculateClothingInsulation);
PREP(updateTemperature);
