/* SPDX-License-Identifier: GPL-2.0-or-later */
// Generated by tools/gen_ownership_sentinels.py. Do not edit by hand.
// Ownership sentinels (ADR-027): one declared property per engine class AEE
// owns. fnc_dumpState reads each live value and reports a mismatch when it is
// not AEE's, which detects a later-loading mod winning the config merge.
// Each entry: [id, config path, property, type, expected AEE value].
[
    ["env-world-lighting", ["CfgWorlds", "CAWorld", "Lighting"], "starEmissivity", "number", 25],
    ["core-sand-cloudlet", ["CfgCloudlets", "AEE_SandCloud"], "interval", "number", 0.005],
    ["core-snow-cloudlet", ["CfgCloudlets", "AEE_SnowCloud"], "interval", "number", 0.01],
    ["fx-supersonic-cloudlet", ["CfgCloudlets", "AEE_SupersonicTrace"], "particleFSNtieth", "number", 1],
    ["thermal-tws-noise", ["CfgWeapons", "optic_tws", "ItemInfo", "OpticsModes", "TWS"], "thermalNoise", "array", [0.05]],
    ["thermal-tws-resolution", ["CfgWeapons", "optic_tws", "ItemInfo", "OpticsModes", "TWS"], "thermalResolution", "array", [640, 480]],
    ["marker-color-aee", ["CfgMarkerColors", "ColorAEE"], "color", "array", [1, 1, 1, 1]],
    ["marker-base-size", ["CfgMarkers", "AEE_MarkerBase"], "size", "number", 32],
    ["map-color-levels", ["RscMapControl"], "colorLevels", "array", [0.7, 0.48, 0.32, 1]],
    ["mobility-mbt-mass", ["CfgVehicles", "B_MBT_01_cannon_F"], "mass", "number", 62273.044493]
]
