#include "script_component.hpp"

AEE_MODULE_PRE_INIT

ADDON = false;

#include "XEH_PREP.hpp"

#include "initSettings.inc.sqf"

// MGRS lettering tables (generated by tools/validation/gen_mgrs_tables.py).
// Loaded once; the format and parse kernels read aee_core_mgrsTables.
aee_core_mgrsTables = call (compile preprocessFileLineNumbers QPATHTOF(data\mgrs_tables.sqf));

// Ownership sentinels (ADR-027): one declared property per engine class AEE
// owns, read by fnc_dumpState to detect a later-loading mod winning the config
// merge for a class AEE owns. Generated by tools/gen_ownership_sentinels.py.
missionNamespace setVariable [QGVAR(ownershipSentinels), call (compile preprocessFileLineNumbers QPATHTOF(data\ownership_sentinels.sqf))];

// Kernel interface (Pillar 2): build the kernel registry and probe the native
// dev extension ONCE here, at preInit.  The dispatcher re-probes once on the
// first dispatch only if this verdict is false, so the hot path never probes.
[] call FUNC(initKernelTable);
[] call FUNC(probeExtension);

missionNamespace setVariable [QGVAR(isReady), true];

ADDON = true;
