#include "script_component.hpp"

AEE_MODULE_PRE_INIT

ADDON = false;

#include "XEH_PREP.hpp"

#include "initSettings.inc.sqf"

// MGRS lettering tables (generated by tools/validation/gen_mgrs_tables.py).
// Loaded once; the format and parse kernels read aee_core_mgrsTables.
aee_core_mgrsTables = call (compile preprocessFileLineNumbers QPATHTOF(data\mgrs_tables.sqf));

missionNamespace setVariable [QGVAR(isReady), true];

ADDON = true;
