// Generated by tools/gen_symbology_modifiers.py.  Do not edit by hand.
// The AEE APP-6 mission-task graphics, amplifier modifiers and echelon
// overlays.  Each icon is a real .paa under data/markers.  markerClass and
// size/shadow come from AEE_MarkerBase in config.cpp.
//
// Geometry source: MIL-STD-2525D (US Government work, public domain) and
// FM 3-90 Appendix B.  The drawn geometry is AEE own work,
// SPDX-License-Identifier: GPL-2.0-or-later.
//
// AEE layers the echelon: the AEE_Ech_* textures carry the ticks in the top
// band of a 64 x 128 canvas, so they sit above a frame marker placed at the
// same position.

    class AEE_MT_Block: AEE_MarkerBase {
        name = "AEE Mission Task Block";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Block.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Block.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Breach: AEE_MarkerBase {
        name = "AEE Mission Task Breach";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Breach.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Breach.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Bypass: AEE_MarkerBase {
        name = "AEE Mission Task Bypass";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Bypass.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Bypass.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Canalize: AEE_MarkerBase {
        name = "AEE Mission Task Canalize";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Canalize.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Canalize.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Clear: AEE_MarkerBase {
        name = "AEE Mission Task Clear";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Clear.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Clear.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Counterattack: AEE_MarkerBase {
        name = "AEE Mission Task Counterattack";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Counterattack.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Counterattack.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Counterattack_by_Fire: AEE_MarkerBase {
        name = "AEE Mission Task Counterattack by Fire";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Counterattack_by_Fire.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Counterattack_by_Fire.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Delay: AEE_MarkerBase {
        name = "AEE Mission Task Delay";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Delay.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Delay.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Destroy: AEE_MarkerBase {
        name = "AEE Mission Task Destroy";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Destroy.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Destroy.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Disrupt: AEE_MarkerBase {
        name = "AEE Mission Task Disrupt";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Disrupt.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Disrupt.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Fix: AEE_MarkerBase {
        name = "AEE Mission Task Fix";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Fix.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Fix.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Follow_and_Assume: AEE_MarkerBase {
        name = "AEE Mission Task Follow and Assume";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Follow_and_Assume.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Follow_and_Assume.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Follow_and_Support: AEE_MarkerBase {
        name = "AEE Mission Task Follow and Support";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Follow_and_Support.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Follow_and_Support.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Interdict: AEE_MarkerBase {
        name = "AEE Mission Task Interdict";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Interdict.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Interdict.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Isolate: AEE_MarkerBase {
        name = "AEE Mission Task Isolate";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Isolate.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Isolate.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Neutralize: AEE_MarkerBase {
        name = "AEE Mission Task Neutralize";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Neutralize.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Neutralize.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Occupy: AEE_MarkerBase {
        name = "AEE Mission Task Occupy";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Occupy.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Occupy.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Penetrate: AEE_MarkerBase {
        name = "AEE Mission Task Penetrate";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Penetrate.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Penetrate.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Relief_in_Place: AEE_MarkerBase {
        name = "AEE Mission Task Relief in Place";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Relief_in_Place.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Relief_in_Place.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Retire: AEE_MarkerBase {
        name = "AEE Mission Task Retire";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Retire.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Retire.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Secure: AEE_MarkerBase {
        name = "AEE Mission Task Secure";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Secure.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Secure.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Security_Cover: AEE_MarkerBase {
        name = "AEE Mission Task Security Cover";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Security_Cover.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Security_Cover.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Security_Guard: AEE_MarkerBase {
        name = "AEE Mission Task Security Guard";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Security_Guard.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Security_Guard.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Security_Screen: AEE_MarkerBase {
        name = "AEE Mission Task Security Screen";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Security_Screen.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Security_Screen.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Seize: AEE_MarkerBase {
        name = "AEE Mission Task Seize";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Seize.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Seize.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Withdraw: AEE_MarkerBase {
        name = "AEE Mission Task Withdraw";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Withdraw.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Withdraw.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Under_Pressure: AEE_MarkerBase {
        name = "AEE Mission Task Under Pressure";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Under_Pressure.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Under_Pressure.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Attack_by_Fire: AEE_MarkerBase {
        name = "AEE Mission Task Attack by Fire";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Attack_by_Fire.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Attack_by_Fire.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Ambush: AEE_MarkerBase {
        name = "AEE Mission Task Ambush";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Ambush.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Ambush.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Contain: AEE_MarkerBase {
        name = "AEE Mission Task Contain";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Contain.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Contain.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Retain: AEE_MarkerBase {
        name = "AEE Mission Task Retain";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Retain.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Retain.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Support_by_Fire: AEE_MarkerBase {
        name = "AEE Mission Task Support by Fire";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Support_by_Fire.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Support_by_Fire.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MT_Turn: AEE_MarkerBase {
        name = "AEE Mission Task Turn";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MT_Turn.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MT_Turn.paa";
        side = 2;
        markerClass = "AEE_Mission_Tasks";
        scope = 0;
    };
    class AEE_MOD_Strength_Reinforced: AEE_MarkerBase {
        name = "AEE Modifier Strength Reinforced";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MOD_Strength_Reinforced.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MOD_Strength_Reinforced.paa";
        side = 2;
        markerClass = "AEE_Modifiers";
        scope = 0;
    };
    class AEE_MOD_Strength_Reduced: AEE_MarkerBase {
        name = "AEE Modifier Strength Reduced";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MOD_Strength_Reduced.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MOD_Strength_Reduced.paa";
        side = 2;
        markerClass = "AEE_Modifiers";
        scope = 0;
    };
    class AEE_MOD_Strength_Both: AEE_MarkerBase {
        name = "AEE Modifier Strength Both";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MOD_Strength_Both.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MOD_Strength_Both.paa";
        side = 2;
        markerClass = "AEE_Modifiers";
        scope = 0;
    };
    class AEE_MOD_Feint_Dummy: AEE_MarkerBase {
        name = "AEE Modifier Feint Dummy";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MOD_Feint_Dummy.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MOD_Feint_Dummy.paa";
        side = 2;
        markerClass = "AEE_Modifiers";
        scope = 0;
    };
    class AEE_MOD_Task_Force_Bracket: AEE_MarkerBase {
        name = "AEE Modifier Task Force Bracket";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MOD_Task_Force_Bracket.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MOD_Task_Force_Bracket.paa";
        side = 2;
        markerClass = "AEE_Modifiers";
        scope = 0;
    };
    class AEE_MOD_HQ_Staff: AEE_MarkerBase {
        name = "AEE Modifier HQ Staff";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MOD_HQ_Staff.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MOD_HQ_Staff.paa";
        side = 2;
        markerClass = "AEE_Modifiers";
        scope = 0;
    };
    class AEE_MOD_Installation: AEE_MarkerBase {
        name = "AEE Modifier Installation";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MOD_Installation.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MOD_Installation.paa";
        side = 2;
        markerClass = "AEE_Modifiers";
        scope = 0;
    };
    class AEE_MOD_Planned_Friend: AEE_MarkerBase {
        name = "AEE Modifier Planned Friend";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MOD_Planned_Friend.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MOD_Planned_Friend.paa";
        side = 2;
        markerClass = "AEE_Modifiers";
        scope = 0;
    };
    class AEE_MOD_Planned_Hostile: AEE_MarkerBase {
        name = "AEE Modifier Planned Hostile";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MOD_Planned_Hostile.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MOD_Planned_Hostile.paa";
        side = 2;
        markerClass = "AEE_Modifiers";
        scope = 0;
    };
    class AEE_MOD_Planned_Neutral: AEE_MarkerBase {
        name = "AEE Modifier Planned Neutral";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MOD_Planned_Neutral.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MOD_Planned_Neutral.paa";
        side = 2;
        markerClass = "AEE_Modifiers";
        scope = 0;
    };
    class AEE_MOD_Planned_Unknown: AEE_MarkerBase {
        name = "AEE Modifier Planned Unknown";
        icon = "\z\aee\addons\symbology\data\markers\AEE_MOD_Planned_Unknown.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_MOD_Planned_Unknown.paa";
        side = 2;
        markerClass = "AEE_Modifiers";
        scope = 0;
    };
    class AEE_Ech_Team: AEE_MarkerBase {
        name = "AEE Echelon Team";
        icon = "\z\aee\addons\symbology\data\markers\AEE_Ech_Team.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_Ech_Team.paa";
        side = 2;
        markerClass = "AEE_Echelon";
        scope = 0;
    };
    class AEE_Ech_Squad: AEE_MarkerBase {
        name = "AEE Echelon Squad";
        icon = "\z\aee\addons\symbology\data\markers\AEE_Ech_Squad.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_Ech_Squad.paa";
        side = 2;
        markerClass = "AEE_Echelon";
        scope = 0;
    };
    class AEE_Ech_Section: AEE_MarkerBase {
        name = "AEE Echelon Section";
        icon = "\z\aee\addons\symbology\data\markers\AEE_Ech_Section.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_Ech_Section.paa";
        side = 2;
        markerClass = "AEE_Echelon";
        scope = 0;
    };
    class AEE_Ech_Platoon: AEE_MarkerBase {
        name = "AEE Echelon Platoon";
        icon = "\z\aee\addons\symbology\data\markers\AEE_Ech_Platoon.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_Ech_Platoon.paa";
        side = 2;
        markerClass = "AEE_Echelon";
        scope = 0;
    };
    class AEE_Ech_Company: AEE_MarkerBase {
        name = "AEE Echelon Company";
        icon = "\z\aee\addons\symbology\data\markers\AEE_Ech_Company.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_Ech_Company.paa";
        side = 2;
        markerClass = "AEE_Echelon";
        scope = 0;
    };
    class AEE_Ech_Battalion: AEE_MarkerBase {
        name = "AEE Echelon Battalion";
        icon = "\z\aee\addons\symbology\data\markers\AEE_Ech_Battalion.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_Ech_Battalion.paa";
        side = 2;
        markerClass = "AEE_Echelon";
        scope = 0;
    };
    class AEE_Ech_Regiment: AEE_MarkerBase {
        name = "AEE Echelon Regiment";
        icon = "\z\aee\addons\symbology\data\markers\AEE_Ech_Regiment.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_Ech_Regiment.paa";
        side = 2;
        markerClass = "AEE_Echelon";
        scope = 0;
    };
    class AEE_Ech_Brigade: AEE_MarkerBase {
        name = "AEE Echelon Brigade";
        icon = "\z\aee\addons\symbology\data\markers\AEE_Ech_Brigade.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_Ech_Brigade.paa";
        side = 2;
        markerClass = "AEE_Echelon";
        scope = 0;
    };
    class AEE_Ech_Division: AEE_MarkerBase {
        name = "AEE Echelon Division";
        icon = "\z\aee\addons\symbology\data\markers\AEE_Ech_Division.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_Ech_Division.paa";
        side = 2;
        markerClass = "AEE_Echelon";
        scope = 0;
    };
    class AEE_Ech_Corps: AEE_MarkerBase {
        name = "AEE Echelon Corps";
        icon = "\z\aee\addons\symbology\data\markers\AEE_Ech_Corps.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_Ech_Corps.paa";
        side = 2;
        markerClass = "AEE_Echelon";
        scope = 0;
    };
    class AEE_Ech_Army: AEE_MarkerBase {
        name = "AEE Echelon Army";
        icon = "\z\aee\addons\symbology\data\markers\AEE_Ech_Army.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_Ech_Army.paa";
        side = 2;
        markerClass = "AEE_Echelon";
        scope = 0;
    };
    class AEE_Ech_Army_Group: AEE_MarkerBase {
        name = "AEE Echelon Army Group";
        icon = "\z\aee\addons\symbology\data\markers\AEE_Ech_Army_Group.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_Ech_Army_Group.paa";
        side = 2;
        markerClass = "AEE_Echelon";
        scope = 0;
    };
    class AEE_Ech_Region: AEE_MarkerBase {
        name = "AEE Echelon Region";
        icon = "\z\aee\addons\symbology\data\markers\AEE_Ech_Region.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_Ech_Region.paa";
        side = 2;
        markerClass = "AEE_Echelon";
        scope = 0;
    };
