// Generated by tools/gen_symbology_catalogue.py.  Do not edit by hand.
// The AEE runtime marker families returned by fnc_symbologyMarkerType.
// Each inherits the real APP-6 catalogue symbol, so its texture, side,
// category and scope survive; only the five glyphs the catalogue does
// not publish inherit AEE_MarkerBase and the produced AEE texture.

    class AEE_u_inf: AEE_MarkerBase {
        name = "AEE Unknown infantry";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_inf.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_inf.paa";
        side = 2;
        markerClass = "AEE_Unknown_Land";
        scope = 2;
    };
    class AEE_u_armor: AEE_MarkerBase {
        name = "AEE Unknown armour";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_armor.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_armor.paa";
        side = 2;
        markerClass = "AEE_Unknown_Land";
        scope = 2;
    };
    class AEE_u_motor_inf: AEE_MarkerBase {
        name = "AEE Unknown motorised";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_motor_inf.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_motor_inf.paa";
        side = 2;
        markerClass = "AEE_Unknown_Land";
        scope = 2;
    };
    class AEE_u_art: AEE_MarkerBase {
        name = "AEE Unknown artillery";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_art.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_art.paa";
        side = 2;
        markerClass = "AEE_Unknown_Land";
        scope = 2;
    };
    class AEE_u_eng: AEE_MarkerBase {
        name = "AEE Unknown engineer";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_eng.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_eng.paa";
        side = 2;
        markerClass = "AEE_Unknown_Land";
        scope = 2;
    };
    class AEE_u_sig: AEE_MarkerBase {
        name = "AEE Unknown signal";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_sig.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_sig.paa";
        side = 2;
        markerClass = "AEE_Unknown_Land";
        scope = 2;
    };
    class AEE_u_med: AEE_MarkerBase {
        name = "AEE Unknown medical";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_med.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_med.paa";
        side = 2;
        markerClass = "AEE_Unknown_Land";
        scope = 2;
    };
    class AEE_u_sup: AEE_MarkerBase {
        name = "AEE Unknown supply";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_sup.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_sup.paa";
        side = 2;
        markerClass = "AEE_Unknown_Land";
        scope = 2;
    };
    class AEE_u_support: AEE_MarkerBase {
        name = "AEE Unknown support";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_support.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_support.paa";
        side = 2;
        markerClass = "AEE_Unknown_Land";
        scope = 2;
    };
    class AEE_u_recon: AEE_MarkerBase {
        name = "AEE Unknown recon";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_recon.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_recon.paa";
        side = 2;
        markerClass = "AEE_Unknown_Land";
        scope = 2;
    };
    class AEE_u_antiair: AEE_MarkerBase {
        name = "AEE Unknown air_defence";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_antiair.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_antiair.paa";
        side = 2;
        markerClass = "AEE_Unknown_Land";
        scope = 2;
    };
    class AEE_u_plane: AEE_MarkerBase {
        name = "AEE Unknown fixed_wing";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_plane.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_plane.paa";
        side = 2;
        markerClass = "AEE_Unknown_Air";
        scope = 2;
    };
    class AEE_u_air: AEE_MarkerBase {
        name = "AEE Unknown rotary";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_air.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_air.paa";
        side = 2;
        markerClass = "AEE_Unknown_Air";
        scope = 2;
    };
    class AEE_u_uav: AEE_MarkerBase {
        name = "AEE Unknown uav";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_uav.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_uav.paa";
        side = 2;
        markerClass = "AEE_Unknown_Air";
        scope = 2;
    };
    class AEE_u_naval: AEE_MarkerBase {
        name = "AEE Unknown sea_surface";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_naval.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_naval.paa";
        side = 2;
        markerClass = "AEE_Unknown_Sea";
        scope = 2;
    };
    class AEE_u_sub: AEE_MarkerBase {
        name = "AEE Unknown subsurface";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_sub.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_sub.paa";
        side = 2;
        markerClass = "AEE_Unknown_Subsurface";
        scope = 2;
    };
    class AEE_u_installation: AEE_MarkerBase {
        name = "AEE Unknown installation";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_installation.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_installation.paa";
        side = 2;
        markerClass = "AEE_Unknown_Installation";
        scope = 2;
    };
    class AEE_u_hq: AEE_MarkerBase {
        name = "AEE Unknown hq";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_hq.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_hq.paa";
        side = 2;
        markerClass = "AEE_Unknown_Land";
        scope = 2;
    };
    class AEE_u_dot: AEE_MarkerBase {
        name = "AEE Unknown waypoint";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_dot.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_dot.paa";
        side = 2;
        markerClass = "AEE_Unknown_Land";
        scope = 2;
    };
    class AEE_u_unknown: AEE_MarkerBase {
        name = "AEE Unknown unknown";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_unknown.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_unknown.paa";
        side = 2;
        markerClass = "AEE_Unknown_Land";
        scope = 2;
    };
    class AEE_b_inf: AEE_FL_Friendly_Unit_Infantry {};
    class AEE_b_armor: AEE_FL_Friendly_Unit_Armour {};
    class AEE_b_motor_inf: AEE_FL_Friendly_Unit_Infantry_Motorized {};
    class AEE_b_art: AEE_FL_Friendly_Unit_Artillery {};
    class AEE_b_eng: AEE_MarkerBase {
        name = "AEE Friendly engineer";
        icon = "\z\aee\addons\symbology\data\markers\AEE_b_eng.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_b_eng.paa";
        side = 1;
        markerClass = "AEE_Friend_Land";
        scope = 2;
    };
    class AEE_b_sig: AEE_MarkerBase {
        name = "AEE Friendly signal";
        icon = "\z\aee\addons\symbology\data\markers\AEE_b_sig.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_b_sig.paa";
        side = 1;
        markerClass = "AEE_Friend_Land";
        scope = 2;
    };
    class AEE_b_med: AEE_FL_Friendly_Unit_Medical {};
    class AEE_b_sup: AEE_MarkerBase {
        name = "AEE Friendly supply";
        icon = "\z\aee\addons\symbology\data\markers\AEE_b_sup.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_b_sup.paa";
        side = 1;
        markerClass = "AEE_Friend_Land";
        scope = 2;
    };
    class AEE_b_support: AEE_FL_Friendly_Unit_CSS_Combat_Service {};
    class AEE_b_recon: AEE_FL_Friendly_Unit_Reconnaissance {};
    class AEE_b_antiair: AEE_FL_Friendly_Unit_Air_Defence {};
    class AEE_b_plane: AEE_FA_Friendly_Unit_Aviation_Fixed_Win {};
    class AEE_b_air: AEE_FA_Friendly_Unit_Aviation {};
    class AEE_b_uav: AEE_FA_Friendly_Unit_Unmanned_Aerial_Ve {};
    class AEE_b_naval: AEE_FS_Friendly_Unit_Naval {};
    class AEE_b_sub: AEE_MarkerBase {
        name = "AEE Friendly subsurface";
        icon = "\z\aee\addons\symbology\data\markers\AEE_b_sub.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_b_sub.paa";
        side = 1;
        markerClass = "AEE_Friend_Subsurface";
        scope = 2;
    };
    class AEE_b_installation: AEE_MarkerBase {
        name = "AEE Friendly installation";
        icon = "\z\aee\addons\symbology\data\markers\AEE_FI_Installation.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_FI_Installation.paa";
        side = 1;
        markerClass = "AEE_Friend_Installation";
        scope = 2;
    };
    class AEE_b_hq: AEE_FL_Friendly_Unit_Headquarters_Unit {};
    class AEE_b_dot: AEE_MarkerBase {
        name = "AEE Friendly waypoint";
        icon = "\z\aee\addons\symbology\data\markers\AEE_b_dot.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_b_dot.paa";
        side = 1;
        markerClass = "AEE_Friend_Land";
        scope = 2;
    };
    class AEE_b_unknown: AEE_MarkerBase {
        name = "AEE Friendly unknown";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_unknown.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_unknown.paa";
        side = 1;
        markerClass = "AEE_Friend_Land";
        scope = 2;
    };
    class AEE_o_inf: AEE_HL_Hostile_Unit_Infantry {};
    class AEE_o_armor: AEE_HL_Hostile_Unit_Armour {};
    class AEE_o_motor_inf: AEE_HL_Hostile_Unit_Infantry_Motorized {};
    class AEE_o_art: AEE_HL_Hostile_Unit_Artillery {};
    class AEE_o_eng: AEE_MarkerBase {
        name = "AEE Hostile engineer";
        icon = "\z\aee\addons\symbology\data\markers\AEE_o_eng.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_o_eng.paa";
        side = 0;
        markerClass = "AEE_Hostile_Land";
        scope = 2;
    };
    class AEE_o_sig: AEE_MarkerBase {
        name = "AEE Hostile signal";
        icon = "\z\aee\addons\symbology\data\markers\AEE_o_sig.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_o_sig.paa";
        side = 0;
        markerClass = "AEE_Hostile_Land";
        scope = 2;
    };
    class AEE_o_med: AEE_HL_Hostile_Unit_Medical {};
    class AEE_o_sup: AEE_MarkerBase {
        name = "AEE Hostile supply";
        icon = "\z\aee\addons\symbology\data\markers\AEE_o_sup.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_o_sup.paa";
        side = 0;
        markerClass = "AEE_Hostile_Land";
        scope = 2;
    };
    class AEE_o_support: AEE_HL_Hostile_Unit_CSS_Combat_Service {};
    class AEE_o_recon: AEE_HL_Hostile_Unit_Reconnaissance {};
    class AEE_o_antiair: AEE_HL_Hostile_Unit_Air_Defence {};
    class AEE_o_plane: AEE_HA_Hostile_Unit_Aviation_Fixed_Wing {};
    class AEE_o_air: AEE_HA_Hostile_Unit_Aviation {};
    class AEE_o_uav: AEE_HA_Hostile_Unit_Unmanned_Aerial_Veh {};
    class AEE_o_naval: AEE_HS_Hostile_Unit_Naval {};
    class AEE_o_sub: AEE_MarkerBase {
        name = "AEE Hostile subsurface";
        icon = "\z\aee\addons\symbology\data\markers\AEE_o_sub.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_o_sub.paa";
        side = 0;
        markerClass = "AEE_Hostile_Subsurface";
        scope = 2;
    };
    class AEE_o_installation: AEE_MarkerBase {
        name = "AEE Hostile installation";
        icon = "\z\aee\addons\symbology\data\markers\AEE_HI_Installation.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_HI_Installation.paa";
        side = 0;
        markerClass = "AEE_Hostile_Installation";
        scope = 2;
    };
    class AEE_o_hq: AEE_HL_Hostile_Unit_Headquarters_Unit {};
    class AEE_o_dot: AEE_MarkerBase {
        name = "AEE Hostile waypoint";
        icon = "\z\aee\addons\symbology\data\markers\AEE_o_dot.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_o_dot.paa";
        side = 0;
        markerClass = "AEE_Hostile_Land";
        scope = 2;
    };
    class AEE_o_unknown: AEE_MarkerBase {
        name = "AEE Hostile unknown";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_unknown.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_unknown.paa";
        side = 0;
        markerClass = "AEE_Hostile_Land";
        scope = 2;
    };
    class AEE_n_inf: AEE_NL_Neutral_Unit_Infantry {};
    class AEE_n_armor: AEE_NL_Neutral_Unit_Armour {};
    class AEE_n_motor_inf: AEE_NL_Neutral_Unit_Infantry {};
    class AEE_n_art: AEE_NL_Neutral_Unit_Artillery {};
    class AEE_n_eng: AEE_MarkerBase {
        name = "AEE Neutral engineer";
        icon = "\z\aee\addons\symbology\data\markers\AEE_n_eng.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_n_eng.paa";
        side = 2;
        markerClass = "AEE_Neutral_Land";
        scope = 2;
    };
    class AEE_n_sig: AEE_MarkerBase {
        name = "AEE Neutral signal";
        icon = "\z\aee\addons\symbology\data\markers\AEE_n_sig.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_n_sig.paa";
        side = 2;
        markerClass = "AEE_Neutral_Land";
        scope = 2;
    };
    class AEE_n_med: AEE_NL_Neutral_Unit_Medical {};
    class AEE_n_sup: AEE_MarkerBase {
        name = "AEE Neutral supply";
        icon = "\z\aee\addons\symbology\data\markers\AEE_n_sup.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_n_sup.paa";
        side = 2;
        markerClass = "AEE_Neutral_Land";
        scope = 2;
    };
    class AEE_n_support: AEE_NL_Neutral_Unit_CSS_Combat_Service {};
    class AEE_n_recon: AEE_NL_Neutral_Unit_Reconnaissance {};
    class AEE_n_antiair: AEE_NL_Neutral_Unit_Air_Defence {};
    class AEE_n_plane: AEE_NA_Neutral_Unit_Aviation_Fixed_Wing {};
    class AEE_n_air: AEE_NA_Neutral_Unit_Aviation {};
    class AEE_n_uav: AEE_NA_Neutral_Unit_Unmanned_Aerial_Veh {};
    class AEE_n_naval: AEE_NS_Neutral_Unit_Naval {};
    class AEE_n_sub: AEE_MarkerBase {
        name = "AEE Neutral subsurface";
        icon = "\z\aee\addons\symbology\data\markers\AEE_n_sub.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_n_sub.paa";
        side = 2;
        markerClass = "AEE_Neutral_Subsurface";
        scope = 2;
    };
    class AEE_n_installation: AEE_MarkerBase {
        name = "AEE Neutral installation";
        icon = "\z\aee\addons\symbology\data\markers\AEE_NI_Installation.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_NI_Installation.paa";
        side = 2;
        markerClass = "AEE_Neutral_Installation";
        scope = 2;
    };
    class AEE_n_hq: AEE_NL_Neutral_Unit_Headquarters_Unit {};
    class AEE_n_dot: AEE_MarkerBase {
        name = "AEE Neutral waypoint";
        icon = "\z\aee\addons\symbology\data\markers\AEE_n_dot.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_n_dot.paa";
        side = 2;
        markerClass = "AEE_Neutral_Land";
        scope = 2;
    };
    class AEE_n_unknown: AEE_MarkerBase {
        name = "AEE Neutral unknown";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_unknown.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_unknown.paa";
        side = 2;
        markerClass = "AEE_Neutral_Land";
        scope = 2;
    };
