// Generated by tools/gen_variation_families.py from
// data/symbology/variation_families.json.  Do not edit by hand.
// The AEE dynamic variation family entries.  Each family is ONE CfgMarkers
// class the picker shows; the concrete variants it resolves to are separate
// classes.  size, shadow and colour restate AEE_MarkerBase.

    class AEE_Variation: AEE_MarkerBase {
        name = "AEE Symbol";
        icon = "\z\aee\addons\symbology\data\markers\AEE_u_inf.paa";
        texture = "\z\aee\addons\symbology\data\markers\AEE_u_inf.paa";
        side = 2;
        markerClass = "AEE_Variation";
        size = 32;
        shadow = 0;
        color[] = {1, 1, 1, 1};
        scope = 2;
    };
