#include "script_component.hpp"

AEE_MODULE_PRE_INIT

ADDON = false;

#include "XEH_PREP.hpp"

// ADR-032 settings migration. The NATO/OPFOR symbology settings moved here
// from aee_optics and took the aee_symbology_* names; copy each set legacy
// value to its new name BEFORE CBA_fnc_addSetting reads it, so a stored value
// survives the rename. The pairs live beside the settings.
[call (compile preprocessFileLineNumbers QPATHTOF(data\settingsMigration.sqf)), "1"] call EFUNC(lib,migrateLegacySettings);

#include "initSettings.inc.sqf"

// NATO/OPFOR symbology category tables (generated by
// tools/validation/gen_symbology_tables.py).  Loaded once; the category
// kernel reads aee_symbology_symbologyTables.
aee_symbology_symbologyTables = call (compile preprocessFileLineNumbers QPATHTOF(data\symbology_tables.sqf));


addMissionEventHandler ["Ended", {
    // disableMapIndicators is a persistent LOCAL effect, not scoped to the
    // map display, so the teardown must reverse it too.  The restore also
    // deletes any AEE markers a map close did not already clear.
    if (hasInterface) then {
        [] call FUNC(symbologyMarkersRestore);
    };
}];

AEE_LOG_INFO("symbology module initialised");

ADDON = true;
