#include "script_component.hpp"

AEE_MODULE_PRE_INIT

ADDON = false;

#include "XEH_PREP.hpp"

// ADR-032 settings migration. The NATO/OPFOR symbology settings moved here
// from aee_optics and took the aee_symbology_* names; copy each set legacy
// value to its new name BEFORE CBA_fnc_addSetting reads it, so a stored value
// survives the rename. The pairs live beside the settings.
[call (compile preprocessFileLineNumbers QPATHTOF(data\settingsMigration.sqf)), "1"] call EFUNC(lib,migrateLegacySettings);

#include "initSettings.inc.sqf"

// NATO/OPFOR symbology category tables (generated by
// tools/validation/gen_symbology_tables.py).  Loaded once; the category
// kernel reads aee_symbology_symbologyTables.
aee_symbology_symbologyTables = call (compile preprocessFileLineNumbers QPATHTOF(data\symbology_tables.sqf));

// The dynamic variation-family model (generated by
// tools/gen_variation_families.py).  Loaded once; the variation kernels read
// aee_symbology_variationFamilies.
aee_symbology_variationFamilies = call (compile preprocessFileLineNumbers QPATHTOF(data\variation_families.sqf));

// The active dynamic variation state: one family's option selection.  The CBA
// LIST settings and the selector dialog write it; the apply layer reads it.  An
// empty state resolves to the family defaults.
aee_symbology_variationState = [];


addMissionEventHandler ["Ended", {
    // disableMapIndicators is a persistent LOCAL effect, not scoped to the
    // map display, so the teardown must reverse it too.  The restore also
    // deletes any AEE markers a map close did not already clear.
    if (hasInterface) then {
        [] call FUNC(symbologyMarkersRestore);
    };
}];

AEE_LOG_INFO("symbology module initialised");

ADDON = true;
