/*
Generated by tools/gen_variation_families.py from
data/symbology/variation_families.json.  Do not edit by hand.  Edit the source
and regenerate.

Each family is [id, label, entry, markerClass, resolver, options].
Each option is [id, label, source, values].
Each value is [id, label, token, grade, source].  The first value of an option
is its family default.
*/

[
    ["symbol", "AEE Symbol", "AEE_Variation", "AEE_Variation", "symbolResolve", [
        ["affiliation", "Affiliation", "families", [
            ["friend", "Friend", "b", "derived", "Arma 3 CfgMarkers NATO BLUFOR family b_; icon \A3\ui_f\data\map\markers\nato\b_*.paa"],
            ["hostile", "Hostile", "o", "derived", "Arma 3 CfgMarkers NATO OPFOR family o_; icon \A3\ui_f\data\map\markers\nato\o_*.paa"],
            ["neutral", "Neutral", "n", "derived", "Arma 3 CfgMarkers NATO Independent family n_; icon \A3\ui_f\data\map\markers\nato\n_*.paa"],
            ["unknown", "Unknown", "u", "derived", "AEE unknown-affiliation family; Arma 3 ships no u_ family, so the AEE u_ textures are produced"],
        ]],
        ["dimension", "Battle Dimension", "dimensions", [
            ["land", "Land", "land", "derived", "tools/symbology_categories.py#ROLES"],
            ["air", "Air", "air", "derived", "tools/symbology_categories.py#ROLES"],
            ["sea", "Sea", "sea", "derived", "tools/symbology_categories.py#ROLES"],
            ["subsurface", "Subsurface", "subsurface", "derived", "tools/symbology_categories.py#ROLES"],
            ["installation", "Installation", "installation", "derived", "tools/symbology_categories.py#ROLES"],
            ["equipment", "Equipment", "equipment", "derived", "tools/symbology_categories.py#ROLES"],
            ["other", "Other", "other", "derived", "tools/symbology_categories.py#ROLES"],
        ]],
        ["function", "Function", "glyphs", [
            ["infantry", "Infantry", "inf", "sourced", "APP-6(C) infantry; Arma 3 b_inf"],
            ["armour", "Armour", "armor", "sourced", "APP-6(C) armour; Arma 3 b_armor"],
            ["motorised", "Motorised", "motor_inf", "derived", "APP-6(C) motorised; Arma 3 b_motor_inf"],
            ["artillery", "Artillery", "art", "sourced", "APP-6(C) artillery; Arma 3 b_art"],
            ["engineer", "Engineer", "eng", "derived", "APP-6(C) engineer; no Arma 3 glyph, AEE produces AEE_*_eng.paa"],
            ["signal", "Signal", "sig", "derived", "APP-6(C) signal; no Arma 3 glyph, AEE produces AEE_*_sig.paa"],
            ["medical", "Medical", "med", "sourced", "APP-6(C) medical; Arma 3 b_med"],
            ["supply", "Supply", "sup", "derived", "APP-6(C) supply; no Arma 3 glyph, AEE produces AEE_*_sup.paa"],
            ["support", "Support", "support", "derived", "APP-6(C) support; Arma 3 b_support"],
            ["recon", "Recon", "recon", "derived", "APP-6(C) reconnaissance; Arma 3 b_recon"],
            ["air_defence", "Air Defence", "antiair", "derived", "APP-6(C) air defence; Arma 3 b_antiair"],
            ["fixed_wing", "Fixed Wing", "plane", "derived", "APP-6(C) fixed wing; Arma 3 b_plane"],
            ["rotary", "Rotary", "air", "derived", "APP-6(C) rotary wing; Arma 3 generic b_air"],
            ["uav", "Uav", "uav", "derived", "APP-6(C) unmanned aerial; Arma 3 b_uav"],
            ["sea_surface", "Sea Surface", "naval", "derived", "APP-6(C) sea surface; Arma 3 b_naval"],
            ["subsurface", "Subsurface", "sub", "derived", "APP-6(C) subsurface; no Arma 3 glyph, AEE produces AEE_*_sub.paa"],
            ["installation", "Installation", "installation", "sourced", "APP-6(C) installation; Arma 3 b_installation"],
            ["hq", "Hq", "hq", "sourced", "APP-6(C) headquarters; Arma 3 b_hq"],
            ["waypoint", "Waypoint", "dot", "derived", "AEE waypoint; no Arma 3 NATO glyph, AEE produces AEE_*_dot.paa"],
            ["unknown", "Unknown", "unknown", "derived", "APP-6(C) unknown; Arma 3 b_unknown"],
        ]],
        ["echelon", "Echelon", "echelons", [
            ["team", "Team", "team", "derived", "MIL-STD-2525D Table D-III"],
            ["squad", "Squad", "squad", "derived", "MIL-STD-2525D Table D-III"],
            ["section", "Section", "section", "derived", "MIL-STD-2525D Table D-III"],
            ["platoon", "Platoon", "platoon", "derived", "MIL-STD-2525D Table D-III"],
            ["company", "Company", "company", "derived", "MIL-STD-2525D Table D-III"],
            ["battalion", "Battalion", "battalion", "derived", "MIL-STD-2525D Table D-III"],
            ["regiment", "Regiment", "regiment", "derived", "MIL-STD-2525D Table D-III"],
            ["brigade", "Brigade", "brigade", "derived", "MIL-STD-2525D Table D-III"],
            ["division", "Division", "division", "derived", "MIL-STD-2525D Table D-III"],
            ["corps", "Corps", "corps", "derived", "MIL-STD-2525D Table D-III"],
            ["army", "Army", "army", "derived", "MIL-STD-2525D Table D-III"],
            ["army_group", "Army Group", "army_group", "derived", "MIL-STD-2525D Table D-III"],
            ["region", "Region", "region", "derived", "MIL-STD-2525D Table D-III"],
        ]],
        ["palette", "Palette", "palette", [
            ["NATO", "NATO", "NATO", "derived", "addons/symbology/initSettings.inc.sqf#symbologyPalette"],
            ["OPFOR", "OPFOR", "OPFOR", "derived", "addons/symbology/initSettings.inc.sqf#symbologyPalette"],
            ["Auto", "Auto", "Auto", "derived", "addons/symbology/initSettings.inc.sqf#symbologyPalette"],
        ]],
    ]]
]
