#include "script_component.hpp"

AEE_MODULE_PRE_INIT

ADDON = false;

#include "XEH_PREP.hpp"

// ADR-032 settings migration. The MGRS map and GPS settings moved here from
// aee_optics and took the aee_cartography_* names; copy each set legacy value
// to its new name BEFORE CBA_fnc_addSetting reads it, so a stored value
// survives the rename. The pairs live beside the settings.
[call (compile preprocessFileLineNumbers QPATHTOF(data\settingsMigration.sqf)), "1"] call EFUNC(lib,migrateLegacySettings);

#include "initSettings.inc.sqf"

// Terrain and map-feature symbol registry (generated by
// tools/validation/gen_terrain_tables.py).  Loaded once; the Docker probe
// reads it to confirm the live config and the registry agree.
aee_cartography_terrainTables = call (compile preprocessFileLineNumbers QPATHTOF(data\terrain_symbols.sqf));


AEE_LOG_INFO("cartography module initialised");

ADDON = true;
