PREP(applyAtmosphericDust);
PREP(applyBreathCondensation);
PREP(applyRainSurfaceDrops);
PREP(applyRainVehicleSound);
PREP(applyVehicleDust);
PREP(applyWindNoise);
PREP(triggerLightning);
PREP(triggerSevereWeatherFX);
PREP(calculateLightningStrikeEffects);
