#include "..\..\script_component.hpp"
/*
 * The fusion emissive material ladder (issue #204, Track B ENVG-B).
 *
 * Returns the 256 material paths, index 0 the darkest through index 255
 * the full A3TI-white emissive.  The set is GENERATED by
 * tools/gen_fusion_emissive_materials.py, so the count is auditable and the
 * set is reproducible.  Build the list ONCE and cache it: the filenames are
 * zero-padded to three digits, and formatting them per selection per tick
 * would grow the hot path for a value that never changes.
 *
 * Pure function: no engine state, no player, no hasInterface.  The P80
 * headless probe calls it directly and asserts count and index order, and
 * fnc_applyFusionOverlay calls it to paint each selection.
 *
 * Params: none.
 *
 * Returns: ARRAY of 256 material path strings.
 */
private _mats = missionNamespace getVariable [QGVAR(fusionEmissiveMats), []];
if (_mats isEqualTo []) then {
    _mats = [];
    for "_mi" from 0 to 255 do {
        private _mn = str _mi;
        while { count _mn < 3 } do { _mn = "0" + _mn; };
        // The rvmat ladder stays with the physics data in aee_thermal (the
        // addon-map keeps addons/thermal/data/** there), so name that addon's
        // path directly rather than QPATHTOF, which would resolve against this
        // display addon and miss the files.
        _mats pushBack format ["\z\aee\addons\thermal\data\fusion_emissive_%1.rvmat", _mn];
    };
    missionNamespace setVariable [QGVAR(fusionEmissiveMats), _mats];
};
_mats
