//! Native kernel coefficients, generated from the SQF reference kernels.
//!
//! Generated by `tools/gen_kernel_coefficients.py` from the named constants
//! in the SQF reference kernels. Do not edit by hand. Run the generator
//! without `--check` to refresh it, with `--check` to fail on drift.

// 14 coefficients.

/// `_T_std` from `addons/atmos/functions/physics/fnc_calculateStationPressure.sqf`.
pub const PRESSURE_T_STD: f64 = 288.15;

/// `_exponent` from `addons/atmos/functions/physics/fnc_calculateStationPressure.sqf`.
pub const PRESSURE_EXPONENT: f64 = 5.2559;

/// `_ratioFloor` from `addons/atmos/functions/physics/fnc_calculateStationPressure.sqf`.
pub const PRESSURE_RATIO_FLOOR: f64 = 0.05;

/// `_diurnalCoef` from `addons/atmos/functions/physics/fnc_calculateRelativeHumidity.sqf`.
pub const HUMIDITY_DIURNAL_COEF: f64 = 0.05;

/// `_overcastGate` from `addons/atmos/functions/physics/fnc_calculateRelativeHumidity.sqf`.
pub const HUMIDITY_OVERCAST_GATE: f64 = 0.7;

/// `_saturation` from `addons/atmos/functions/physics/fnc_calculateRelativeHumidity.sqf`.
pub const HUMIDITY_SATURATION: f64 = 100.0;

/// `_buckA` from `addons/ballistics/functions/fnc_calculateAirDensityKernel.sqf`.
pub const BUCK_A: f64 = 6.1121;

/// `_buckB` from `addons/ballistics/functions/fnc_calculateAirDensityKernel.sqf`.
pub const BUCK_B: f64 = 18.678;

/// `_buckC` from `addons/ballistics/functions/fnc_calculateAirDensityKernel.sqf`.
pub const BUCK_C: f64 = 234.5;

/// `_buckD` from `addons/ballistics/functions/fnc_calculateAirDensityKernel.sqf`.
pub const BUCK_D: f64 = 257.14;

/// `_virtualTempCoef` from `addons/ballistics/functions/fnc_calculateAirDensityKernel.sqf`.
pub const VIRTUAL_TEMP_COEF: f64 = 0.37802;

/// `_kelvinOffset` from `addons/ballistics/functions/fnc_calculateAirDensityKernel.sqf`.
pub const KELVIN_OFFSET: f64 = 273.15;

/// `_specificGasDry` from `addons/ballistics/functions/fnc_calculateAirDensityKernel.sqf`.
pub const SPECIFIC_GAS_DRY: f64 = 287.05287;

/// `_paPerHpa` from `addons/ballistics/functions/fnc_calculateAirDensityKernel.sqf`.
pub const PA_PER_HPA: f64 = 100.0;
