#!/usr/bin/env python3
"""Regenerate docs/wiki/annexes/annex-d-debug-index.qmd from the sources.

One row per addon records the three things an operator needs to trace a
module: its ``AEE Debug`` switch, its state-dump function, and its force
hooks.  Three readers feed the row:

  1. addons/*/initSettings.inc.sqf for every setting under the ``AEE Debug``
     category.  The settings parser in gen_config_docs handles both the
     AEE_SETTING_* macro form and the explicit CBA_fnc_addSetting form.
  2. addons/*/functions/**/fnc_log*State.sqf and fnc_dump*.sqf for the state
     dump.
  3. every QGVAR(*Force*) and (Q)EGVAR(*, *Force*) read under addons/ for the
     force hooks.  A hook read through EGVAR belongs to the addon it names.

Write mode refuses to remove a module the file already lists unless
--allow-removals is given, so a parser regression cannot silently truncate
the annex.  --check compares the file with the sources and exits non-zero on
drift.

Run from the repo root:

    python3 tools/validation/gen_debug_index.py            # write the file
    python3 tools/validation/gen_debug_index.py --check    # compare, no write
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ADDONS = REPO / "addons"
DOC = REPO / "docs/wiki/annexes/annex-d-debug-index.qmd"

# Modules that publish no debug switch, no state dump and no force hook, so
# they do not earn a row.  The reason travels with the name.
EXEMPTIONS: dict[str, str] = {
    "lib": "lib holds macros and config only and publishes no state",
}

# Reuse the settings parser so the macro form and the long form both resolve.
sys.path.insert(0, str(Path(__file__).resolve().parent))
import gen_config_docs  # noqa: E402

_ROW_IN_DOC = re.compile(r"^\|\s*`?([a-z_][a-z0-9_]*)`?\s*\|")
_QGVAR_FORCE = re.compile(r"QGVAR\((\w*Force\w*)\)")
_QEGVAR_FORCE = re.compile(r"Q?EGVAR\((\w+),\s*(\w*Force\w*)\)")

INTRO = (
    "Generated by `tools/validation/gen_debug_index.py`. Do not edit by "
    "hand. A debug switch registers under `AEE Debug` and turns the module "
    "trace on. A state dump emits one structured line of the module state. "
    "A force hook overrides one computed value for a test. The `-` cell "
    "means the module has no item in that column."
)


@dataclass(frozen=True, slots=True)
class Module:
    """One addon row of the debug index."""

    name: str
    switches: tuple[str, ...]
    dumps: tuple[str, ...]
    hooks: tuple[str, ...]


def debug_switches() -> dict[str, list[str]]:
    """Every AEE Debug setting, grouped by its addon."""
    found: dict[str, list[str]] = {}
    for setting in gen_config_docs.collect_settings():
        if setting.category == "AEE Debug":
            found.setdefault(setting.addon, []).append(setting.name)
    return found


def state_dumps() -> dict[str, list[str]]:
    """The state-dump function in each addon, if any."""
    found: dict[str, list[str]] = {}
    patterns = ("*/functions/**/fnc_log*State.sqf", "*/functions/**/fnc_dump*.sqf")
    for pattern in patterns:
        for path in ADDONS.glob(pattern):
            addon = path.relative_to(ADDONS).parts[0]
            name = f"aee_{addon}_{path.stem}"
            found.setdefault(addon, []).append(name)
    return found


def force_hooks() -> dict[str, list[str]]:
    """Every force hook read, attributed to the addon that owns the variable.

    A QGVAR read belongs to the addon that contains the file.  A (Q)EGVAR
    read names its owning addon in the first argument.
    """
    found: dict[str, list[str]] = {}
    for path in sorted(ADDONS.rglob("*.sqf")):
        addon = path.relative_to(ADDONS).parts[0]
        text = gen_config_docs.strip_comments(path.read_text(encoding="utf-8"))
        for match in _QGVAR_FORCE.finditer(text):
            found.setdefault(addon, []).append(f"aee_{addon}_{match.group(1)}")
        for match in _QEGVAR_FORCE.finditer(text):
            owner, hook = match.group(1), match.group(2)
            found.setdefault(owner, []).append(f"aee_{owner}_{hook}")
    return found


def all_addons() -> list[str]:
    """Every addon directory, sorted."""
    return sorted(p.name for p in ADDONS.iterdir() if p.is_dir())


def collect_modules() -> list[Module]:
    """Every non-exempt addon with its three columns, sorted by name."""
    switches = debug_switches()
    dumps = state_dumps()
    hooks = force_hooks()
    modules: list[Module] = []
    for name in all_addons():
        if name in EXEMPTIONS:
            continue
        modules.append(
            Module(
                name=name,
                switches=tuple(sorted(set(switches.get(name, [])))),
                dumps=tuple(sorted(set(dumps.get(name, [])))),
                hooks=tuple(sorted(set(hooks.get(name, [])))),
            )
        )
    return modules


def cell(items: tuple[str, ...]) -> str:
    """A single-line markdown table cell, or `-` when empty."""
    if not items:
        return "-"
    return "<br>".join(f"`{item}`" for item in items)


def render(modules: list[Module]) -> str:
    """Render the complete annex."""
    lines: list[str] = [
        "---",
        'title: "Annex D - Debug index"',
        "---",
        "",
        "# Annex D: Debug index {#sec-annex-d-debug-index}",
        "",
        INTRO,
        "",
        "| Module | Debug switch | State dump | Force hooks |",
        "|---|---|---|---|",
    ]
    for module in modules:
        lines.append(
            f"| `{module.name}` | {cell(module.switches)} | "
            f"{cell(module.dumps)} | {cell(module.hooks)} |"
        )
    lines.append("")
    if EXEMPTIONS:
        lines.append("Modules with no row:")
        lines.append("")
        for name in sorted(EXEMPTIONS):
            lines.append(f"- `{name}` - {EXEMPTIONS[name]}")
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def modules_in_doc(text: str) -> set[str]:
    """The module names a rendered annex already lists."""
    found: set[str] = set()
    for line in text.splitlines():
        match = _ROW_IN_DOC.match(line)
        if match and match.group(1) != "module":
            found.add(match.group(1))
    return found


def check(path: Path = DOC) -> int:
    """Return 0 when the file equals the generated text, 1 otherwise."""
    rendered = render(collect_modules())
    if not path.exists():
        print(f"missing: {path}")
        return 1
    if path.read_text(encoding="utf-8") != rendered:
        print(f"stale: {path}")
        return 1
    print(f"fresh: {path}")
    return 0


def write(path: Path = DOC, allow_removals: bool = False) -> int:
    modules = collect_modules()
    rendered = render(modules)
    if path.exists() and not allow_removals:
        missing = modules_in_doc(path.read_text(encoding="utf-8")) - {
            module.name for module in modules
        }
        if missing:
            print(
                "refusing to write: the new document would drop "
                f"{len(missing)} module row(s): {', '.join(sorted(missing))}"
            )
            return 1
    path.write_text(rendered, encoding="utf-8")
    print(f"wrote {len(modules)} module rows to {path}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="compare, do not write")
    parser.add_argument(
        "--allow-removals",
        action="store_true",
        help="permit a write that removes an already-listed module row",
    )
    args = parser.parse_args(argv)
    if args.check:
        return check()
    return write(allow_removals=args.allow_removals)


if __name__ == "__main__":
    sys.exit(main())
