#!/usr/bin/env python3
"""Render a human-readable index of the ballistics database.

Writes data/ballistics/INDEX.md: one section per cartridge type, sorted
by calibre, with the held values and their grade. A person can read the
file directly or grep it.

Run:  python3 tools/validation/render_ballistics_index.py
"""

import json
from pathlib import Path

DATA = Path(__file__).parents[2] / "data" / "ballistics"
OUT = DATA / "INDEX.md"
ORDER = [
    "rifle",
    "pistol",
    "rimfire",
    "shotgun",
    "industrial",
    "alarm",
    "caseless",
    "other",
    "(unclassified)",
]


def cell(rec, field):
    entry = rec.get("values", {}).get(field)
    return entry["value"] if entry else ""


def main():
    db = json.loads((DATA / "cartridges.json").read_text(encoding="utf-8"))
    groups = {}
    for rec in db:
        groups.setdefault(
            rec.get("classification", {}).get("cartridge_type", "(unclassified)"), []
        ).append(rec)

    lines = [
        "# Ballistics database index",
        "",
        "Generated by `tools/validation/render_ballistics_index.py`.",
        "Do not edit by hand.",
        "",
        f"Cartridges: {len(db)}. Source: CIP TDCC, held under "
        "`data/ballistics/sources/cip/`.",
        "Every value carries a source and a grade, checked by "
        "`tools/validation/validate_ballistics_data.py`.",
        "",
        "## Summary",
        "",
        "| Cartridge type | Count |",
        "|---|---|",
    ]
    for kind in ORDER:
        if kind in groups:
            lines.append(f"| {kind} | {len(groups[kind])} |")
    lines.append("")

    for kind in ORDER:
        if kind not in groups:
            continue
        rows = sorted(
            groups[kind],
            key=lambda r: (
                float(cell(r, "calibre_mm") or 1e9),
                float(cell(r, "case_length_mm") or 1e9),
                r["cartridge_id"],
            ),
        )
        lines += [
            f"## {kind} ({len(rows)})",
            "",
            "| ID | Name | Calibre mm | Case mm | Pressure MPa | Twist m/turn | Grooves | Grade |",
            "|---|---|---|---|---|---|---|---|",
        ]
        for rec in rows:
            grades = sorted({e.get("grade", "") for e in rec["values"].values()})
            names = rec.get("names", [])
            lines.append(
                f"| {rec['cartridge_id']} | {names[0] if names else ''} "
                f"| {cell(rec, 'calibre_mm')} | {cell(rec, 'case_length_mm')} "
                f"| {cell(rec, 'max_pressure_mpa')} | {cell(rec, 'standard_twist_m')} "
                f"| {cell(rec, 'grooves')} | {','.join(grades)} |"
            )
        lines.append("")

    projectiles = json.loads((DATA / "projectiles.json").read_text(encoding="utf-8"))
    if projectiles:
        rows = sorted(
            projectiles,
            key=lambda r: (
                float(cell(r, "diameter_mm") or 1e9),
                float(cell(r, "mass_g") or 1e9),
                r["projectile_id"],
            ),
        )
        lines += [
            f"## projectiles ({len(rows)})",
            "",
            "| ID | Name | Manufacturer | Mass g | Diameter mm | BC G1 | BC G7 | SD | Grade |",
            "|---|---|---|---|---|---|---|---|---|",
        ]
        for rec in rows:
            grades = sorted({e.get("grade", "") for e in rec["values"].values()})
            names = rec.get("names", [])
            lines.append(
                f"| {rec['projectile_id']} | {names[0] if names else ''} "
                f"| {rec.get('manufacturer', '')} | {cell(rec, 'mass_g')} "
                f"| {cell(rec, 'diameter_mm')} | {cell(rec, 'bc_g1')} "
                f"| {cell(rec, 'bc_g7')} | {cell(rec, 'sectional_density')} "
                f"| {','.join(grades)} |"
            )
        lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"wrote {OUT} ({len(db)} cartridges, {len(projectiles)} projectiles, "
        f"{len(OUT.read_text(encoding='utf-8').splitlines())} lines)"
    )


if __name__ == "__main__":
    main()
