#!/usr/bin/env python3
"""Generate the native kernel coefficient table from the SQF reference kernels.

The native kernels must use the SAME numeric coefficients as their SQF
reference, or the two paths drift.  Rather than type each constant twice, this
generator reads the named `private _x = <number>;` constants out of the SQF
reference kernels and emits them as Rust constants.  The extension compiles the
generated file; `--check` fails when it is stale.

The extension builds in a container that mounts only the extension directory,
so a Rust build script cannot read `addons/`.  This generator is the
repo-consistent equivalent: a committed table plus a `--check` gate.

Run:
    python3 tools/gen_kernel_coefficients.py           # write the table
    python3 tools/gen_kernel_coefficients.py --check   # fail on drift
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parents[1]
OUT = (
    ROOT / "tools" / "dev-harness" / "extension" / "src" / "kernels" / "coefficients.rs"
)

# (SQF reference kernel, SQF constant, Rust constant)
COEFFICIENTS: tuple[tuple[str, str, str], ...] = (
    (
        "addons/atmos/functions/physics/fnc_calculateStationPressure.sqf",
        "_T_std",
        "PRESSURE_T_STD",
    ),
    (
        "addons/atmos/functions/physics/fnc_calculateStationPressure.sqf",
        "_exponent",
        "PRESSURE_EXPONENT",
    ),
    (
        "addons/atmos/functions/physics/fnc_calculateStationPressure.sqf",
        "_ratioFloor",
        "PRESSURE_RATIO_FLOOR",
    ),
    (
        "addons/atmos/functions/physics/fnc_calculateRelativeHumidity.sqf",
        "_diurnalCoef",
        "HUMIDITY_DIURNAL_COEF",
    ),
    (
        "addons/atmos/functions/physics/fnc_calculateRelativeHumidity.sqf",
        "_overcastGate",
        "HUMIDITY_OVERCAST_GATE",
    ),
    (
        "addons/atmos/functions/physics/fnc_calculateRelativeHumidity.sqf",
        "_saturation",
        "HUMIDITY_SATURATION",
    ),
    (
        "addons/ballistics/functions/fnc_calculateAirDensityKernel.sqf",
        "_buckA",
        "BUCK_A",
    ),
    (
        "addons/ballistics/functions/fnc_calculateAirDensityKernel.sqf",
        "_buckB",
        "BUCK_B",
    ),
    (
        "addons/ballistics/functions/fnc_calculateAirDensityKernel.sqf",
        "_buckC",
        "BUCK_C",
    ),
    (
        "addons/ballistics/functions/fnc_calculateAirDensityKernel.sqf",
        "_buckD",
        "BUCK_D",
    ),
    (
        "addons/ballistics/functions/fnc_calculateAirDensityKernel.sqf",
        "_virtualTempCoef",
        "VIRTUAL_TEMP_COEF",
    ),
    (
        "addons/ballistics/functions/fnc_calculateAirDensityKernel.sqf",
        "_kelvinOffset",
        "KELVIN_OFFSET",
    ),
    (
        "addons/ballistics/functions/fnc_calculateAirDensityKernel.sqf",
        "_specificGasDry",
        "SPECIFIC_GAS_DRY",
    ),
    (
        "addons/ballistics/functions/fnc_calculateAirDensityKernel.sqf",
        "_paPerHpa",
        "PA_PER_HPA",
    ),
)

CONST_RE = re.compile(
    r"^\s*private\s+(?P<name>_[A-Za-z0-9_]+)\s*=\s*"
    r"(?P<value>[0-9]+(?:\.[0-9]+)?|[A-Za-z_][A-Za-z0-9_]*)\s*;",
    re.M,
)

CONSTANTS_HPP = ROOT / "addons" / "lib" / "constants.hpp"
DEFINE_RE = re.compile(r"^#define\s+([A-Za-z_]\w*)\s+([0-9]+(?:\.[0-9]+)?)", re.M)


def _resolve(value: str) -> str:
    """A bare number passes through; a shared-constant name is read from
    addons/lib/constants.hpp, so a kernel can name the constant instead of
    repeating the literal."""
    if re.fullmatch(r"[0-9]+(?:\.[0-9]+)?", value):
        return value
    text = CONSTANTS_HPP.read_text(encoding="utf-8")
    for name, number in DEFINE_RE.findall(text):
        if name == value:
            return number
    raise SystemExit(f"gen_kernel_coefficients: {value} not defined in {CONSTANTS_HPP}")


def extract(rel: str, var: str) -> str:
    """Return the literal assigned to `var` in the SQF file `rel`."""
    text = (ROOT / rel).read_text(encoding="utf-8")
    for match in CONST_RE.finditer(text):
        if match.group("name") == var:
            return _resolve(match.group("value"))
    raise SystemExit(f"gen_kernel_coefficients: {rel}: constant {var} not found")


def build() -> str:
    lines = [
        "//! Native kernel coefficients, generated from the SQF reference kernels.",
        "//!",
        "//! Generated by `tools/gen_kernel_coefficients.py` from the named constants",
        "//! in the SQF reference kernels. Do not edit by hand. Run the generator",
        "//! without `--check` to refresh it, with `--check` to fail on drift.",
        "",
        f"// {len(COEFFICIENTS)} coefficients.",
        "",
    ]
    for rel, var, rust in COEFFICIENTS:
        value = extract(rel, var)
        if "." not in value:
            value += ".0"
        lines.append(f"/// `{var}` from `{rel}`.")
        lines.append(f"pub const {rust}: f64 = {value};")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail on drift, write nothing"
    )
    args = parser.parse_args()

    block = build()
    if args.check:
        if not OUT.is_file() or OUT.read_text(encoding="utf-8") != block:
            print("kernel coefficients: stale (run without --check)")
            return 1
        print(f"kernel coefficients: PASS ({len(COEFFICIENTS)} constants)")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(block, encoding="utf-8")
    print(f"kernel coefficients: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
