#!/usr/bin/env python3
"""Generate the AEE APP-6 marker legend from the pulled catalogue.

The engine marker set is generated by tools/gen_symbology_catalogue.py from
data/symbology/nato_catalogue.json.  That generator names each marker the same
way every time, so this legend can name the same marker and join the two
outputs.

For each catalogue symbol this generator records:

  * the generated marker id (from tools/gen_symbology_catalogue.py),
  * the affiliation, battle dimension, function and frame of the source,
  * the source file, source URL, licence and author of the image, and
  * the engine marker classes the marker re-textures, read from the override
    block of addons/optics/config_markers.hpp.

It emits data/symbology/app6_catalogue.json and docs/wiki/research/app6-catalogue.md
(a human legend, grouped by affiliation and then by battle dimension).

Run:  python3 tools/gen_app6_catalogue.py
      python3 tools/gen_app6_catalogue.py --check
      python3 tools/gen_app6_catalogue.py --table
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools import gen_symbology_catalogue as sym  # noqa: E402

CATALOGUE = ROOT / "data" / "symbology" / "nato_catalogue.json"
CONFIG_MARKERS = ROOT / "addons" / "symbology" / "config_markers.hpp"
OUT = ROOT / "data" / "symbology" / "app6_catalogue.json"
MARKDOWN = ROOT / "docs" / "wiki" / "research" / "app6-catalogue.md"
MARKER_REL = "addons/symbology/data/markers"

AFFIL_ORDER = ["Friend", "Hostile", "Neutral", "Unknown"]
DIM_ORDER = [
    "Land",
    "Air/Space",
    "Sea Surface",
    "Subsurface",
    "Installation",
    "Equipment",
]

NOTE = (
    "Generated legend for the AEE APP-6 map markers. Each row names one marker, "
    "its source image and the engine marker classes it re-textures. The used_for "
    "field names those engine classes, or null when no engine class uses the "
    "marker. Do not edit this file by hand."
)
ATTRIBUTION = (
    "Contains NATO APP-6 and MIL-STD-2525 symbol designs pulled from Wikimedia "
    "Commons and en.wikipedia. Each marker keeps the licence of its source image. "
    "See the source_url and licence fields of each row."
)
SOURCE = (
    "data/symbology/nato_catalogue.json "
    "(Wikimedia Commons and en.wikipedia APP-6 marker pull)"
)

# The engine overrides are written one per line by tools/gen_symbology_catalogue.py.
_OVERRIDE_RE = re.compile(r'class (\w+) \{ icon = "([^"]+)"; texture = "([^"]+)"; \};')


def override_map() -> dict[str, list[str]]:
    """Map each generated marker id to the engine classes that re-texture it."""
    text = CONFIG_MARKERS.read_text(encoding="utf-8")
    block = text.split("// Overwrite the engine")[-1]
    out: dict[str, list[str]] = {}
    for match in _OVERRIDE_RE.finditer(block):
        engine_class = match.group(1)
        icon = match.group(2)
        asset = icon.replace("\\", "/").rsplit("/", 1)[-1]
        if asset.endswith(".paa"):
            asset = asset[:-4]
        out.setdefault(asset, []).append(engine_class)
    for classes in out.values():
        classes.sort()
    return out


def build_entries() -> list[dict[str, Any]]:
    overrides = override_map()
    rows: list[dict[str, Any]] = []
    for name, entry in sym.entries():
        classes = overrides.get(name, [])
        rows.append(
            {
                "id": name,
                "kind": entry.get("kind", "symbol"),
                "affiliation": entry.get("affil", ""),
                "dimension": entry.get("dim", ""),
                "function": entry.get("func", ""),
                "frame": entry.get("frame", ""),
                "source_file": entry.get("file", ""),
                "source_url": entry.get("url", ""),
                "licence": entry.get("license", ""),
                "author": entry.get("artist", ""),
                "used_for": ", ".join(classes) if classes else None,
                "preview": f"{MARKER_REL}/{name}.paa",
            }
        )
    return rows


def build_document() -> dict[str, Any]:
    rows = build_entries()
    return {
        "note": NOTE,
        "attribution": ATTRIBUTION,
        "source": SOURCE,
        "count": len(rows),
        "entries": rows,
    }


def render_json(document: dict[str, Any]) -> str:
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def _cell(value: Any) -> str:
    text = "" if value is None else str(value)
    return text.replace("|", "\\|")


def _ordered(values: list[str], order: list[str]) -> list[str]:
    known = [v for v in order if v in values]
    extra = sorted(v for v in values if v not in order)
    return known + extra


def render_markdown(document: dict[str, Any]) -> str:
    rows = document["entries"]
    lines = [
        "# AEE APP-6 marker catalogue",
        "",
        "This file is the human legend of the AEE APP-6 map markers. The generator",
        "tools/gen_app6_catalogue.py writes it from "
        "data/symbology/nato_catalogue.json.",
        "Do not edit it by hand.",
        "",
        "The catalogue groups the markers by affiliation and then by battle",
        "dimension. The used_for column names the engine marker class the marker",
        "re-textures. The value none means the marker has no engine override.",
        "",
        f"Marker count: {document['count']}.",
        "",
        f"Attribution: {document['attribution']}",
        "",
    ]
    by_affil: dict[str, dict[str, list[dict[str, Any]]]] = {}
    for row in rows:
        by_affil.setdefault(row["affiliation"], {}).setdefault(
            row["dimension"], []
        ).append(row)
    for affil in _ordered(list(by_affil), AFFIL_ORDER):
        lines += [f"## {affil or 'Unspecified'}", ""]
        dims = by_affil[affil]
        for dim in _ordered(list(dims), DIM_ORDER):
            lines += [f"### {dim or 'Unspecified'}", ""]
            lines += [
                "| id | affiliation | dimension | function | used_for | licence | author |",
                "|---|---|---|---|---|---|---|",
            ]
            for row in dims[dim]:
                used = row["used_for"] if row["used_for"] is not None else "none"
                lines.append(
                    "| "
                    + " | ".join(
                        _cell(v)
                        for v in (
                            row["id"],
                            row["affiliation"],
                            row["dimension"],
                            row["function"],
                            used,
                            row["licence"],
                            row["author"],
                        )
                    )
                    + " |"
                )
            lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def build() -> int:
    document = build_document()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    MARKDOWN.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render_json(document), encoding="utf-8")
    MARKDOWN.write_text(render_markdown(document), encoding="utf-8")
    print(f"app6 catalogue: {document['count']} markers written")
    return 0


def stale_reasons() -> list[str]:
    document = build_document()
    stale: list[str] = []
    if not OUT.is_file() or OUT.read_text(encoding="utf-8") != render_json(document):
        stale.append("data/symbology/app6_catalogue.json is stale")
    if not MARKDOWN.is_file() or MARKDOWN.read_text(
        encoding="utf-8"
    ) != render_markdown(document):
        stale.append("docs/wiki/research/app6-catalogue.md is stale")
    for row in document["entries"]:
        if not (ROOT / row["preview"]).is_file():
            stale.append(f"{row['id']}.paa is missing")
    return stale


def check() -> int:
    stale = stale_reasons()
    if stale:
        print(f"app6 catalogue: FAIL ({len(stale)})")
        for line in stale:
            print(f"  {line}")
        return 1
    print(f"app6 catalogue: {build_document()['count']} markers fresh")
    return 0


def table() -> int:
    for row in build_entries():
        print(
            f"{row['id']}\t{row['affiliation']}\t{row['dimension']}\t"
            f"{row['function']}\t{row['used_for'] or '-'}\t"
            f"{row['licence']}\t{row['preview']}"
        )
    return 0


def main(argv: list[str]) -> int:
    if "--check" in argv:
        return check()
    if "--table" in argv:
        return table()
    return build()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
