#!/usr/bin/env python3
"""Generate the native drag table from the SQF reference kernel.

The native drag kernel must use the SAME standard drag tables as its SQF
reference (`fnc_getDragTables.sqf`), or the two drift.  Rather than type the
tables a second time, this generator reads them out of the SQF source and
emits a Rust constant.  The extension builds in a container that mounts only
the extension directory, so a Rust build script cannot read `addons/`; this is
the repo-consistent equivalent: a committed table plus a `--check` gate.

Run:
    python3 tools/gen_kernel_drag_tables.py           # write the table
    python3 tools/gen_kernel_drag_tables.py --check   # fail on drift
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT / "tools"))

from gen_kernel_vectors import load_drag_tables  # noqa: E402

OUT = (
    ROOT / "tools" / "dev-harness" / "extension" / "src" / "kernels" / "drag_tables.rs"
)


def build() -> str:
    tables = load_drag_tables()
    lines = [
        "//! The standard drag tables, generated from the SQF reference kernel.",
        "//!",
        "//! Generated by `tools/gen_kernel_drag_tables.py` from",
        "//! `addons/ballistics/functions/fnc_getDragTables.sqf`. Do not edit by hand.",
        "//! Run the generator without `--check` to refresh it, with `--check` to",
        "//! fail on drift.",
        "",
        f"// {len(tables)} models.",
        "",
        "pub const DRAG_TABLES: &[(&str, &[(f64, f64)])] = &[",
    ]
    for name in sorted(tables):
        points = tables[name]
        rendered = ", ".join(f"({mach:.3f}, {cd:.4f})" for mach, cd in points)
        lines.append(f'    ("{name}", &[{rendered}]),')
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail on drift, write nothing"
    )
    args = parser.parse_args()

    block = build()
    if args.check:
        if not OUT.is_file() or OUT.read_text(encoding="utf-8") != block:
            print("kernel drag tables: stale (run without --check)")
            return 1
        print(f"kernel drag tables: PASS ({len(load_drag_tables())} models)")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(block, encoding="utf-8")
    print(f"kernel drag tables: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
