#!/usr/bin/env python3
"""Generate the AEE dynamic variation-family artifacts.

The validated source is data/symbology/variation_families.json.  This
generator DERIVES each option's value list from the table named in the option's
`source` and writes two artifacts:

  addons/symbology/config_variations.hpp   the CfgMarkers family entry
  addons/symbology/data/variation_families.sqf   the runtime model

No value is hand-listed.  A new symbol in a shipped table becomes a new option
value with no edit to the source.

The derivation per source:

  families    the families section of symbology_tables.json: the affiliation
              rows friend/b, hostile/o, neutral/n, unknown/u
  dimensions  ROLES in tools/symbology_categories.py: the CfgMarkerClasses
              subcategories Land, Air, Sea, Subsurface, Installation,
              Equipment, Other
  glyphs      the glyphs section of symbology_tables.json: each glyph name and
              its marker token
  echelons    the echelon markers in modifiers.json: each AEE_Ech_* class and
              its title
  palette     the symbologyPalette choices: NATO, OPFOR, Auto

The order is fixed, so the output is byte-stable.  The `--check` mode writes
nothing and returns 1 when an artifact differs from a fresh render.

Run:  python3 tools/gen_variation_families.py
      python3 tools/gen_variation_families.py --check
      python3 tools/gen_variation_families.py --table
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).parents[1]
if str(Path(__file__).parent) not in sys.path:
    sys.path.insert(0, str(Path(__file__).parent))

from symbology_categories import ROLES  # noqa: E402

FAMILIES_JSON = ROOT / "data" / "symbology" / "variation_families.json"
TABLES_JSON = ROOT / "data" / "symbology" / "symbology_tables.json"
MODIFIERS_JSON = ROOT / "data" / "symbology" / "modifiers.json"
CONFIG_OUT = ROOT / "addons" / "symbology" / "config_variations.hpp"
MODEL_OUT = ROOT / "addons" / "symbology" / "data" / "variation_families.sqf"

MARKER_PREFIX = "\\z\\aee\\addons\\symbology\\data\\markers"
# A real committed AEE texture.  The entry is one icon in the picker; the
# operator re-types it in game, so its own texture is only the picker preview.
ENTRY_TEXTURE = "AEE_u_inf.paa"
PALETTES = ("NATO", "OPFOR", "Auto")
ECHELON_PREFIX = "AEE_Ech_"

CONFIG_HEADER = (
    "// Generated by tools/gen_variation_families.py from\n"
    "// data/symbology/variation_families.json.  Do not edit by hand.\n"
    "// The AEE dynamic variation family entries.  Each family is ONE CfgMarkers\n"
    "// class the picker shows; the concrete variants it resolves to are separate\n"
    "// classes.  size, shadow and colour restate AEE_MarkerBase.\n"
)

MODEL_HEADER = """/*
Generated by tools/gen_variation_families.py from
data/symbology/variation_families.json.  Do not edit by hand.  Edit the source
and regenerate.

Each family is [id, label, entry, markerClass, resolver, options].
Each option is [id, label, source, values].
Each value is [id, label, token, grade, source].  The first value of an option
is its family default.
*/
"""


def sqf_str(value: str) -> str:
    """A double-quoted SQF string, with the embedded quote doubled."""
    return '"' + value.replace('"', '""') + '"'


def sqf_value(value: Any) -> str:
    if isinstance(value, str):
        return sqf_str(value)
    if isinstance(value, list):
        return "[" + ", ".join(sqf_value(item) for item in value) + "]"
    return str(value)


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def derive_values(source: str, tables: dict, modifiers: dict) -> list[list[str]]:
    """The value rows [id, label, token, grade, source] for one option."""
    if source == "families":
        return [
            [
                row["name"],
                row["name"].title(),
                row["category"],
                row["grade"],
                row["source"],
            ]
            for row in tables["families"]
        ]
    if source == "dimensions":
        return [
            [
                role.lower(),
                role,
                role.lower(),
                "derived",
                "tools/symbology_categories.py#ROLES",
            ]
            for role in ROLES
        ]
    if source == "glyphs":
        return [
            [
                row["name"],
                row["name"].replace("_", " ").title(),
                row["category"],
                row["grade"],
                row["source"],
            ]
            for row in tables["glyphs"]
        ]
    if source == "echelons":
        return [
            [
                marker["name"].replace(ECHELON_PREFIX, "").lower(),
                marker["title"],
                marker["name"].replace(ECHELON_PREFIX, "").lower(),
                "derived",
                marker["source"],
            ]
            for marker in modifiers["markers"]
            if marker["kind"] == "echelon"
        ]
    if source == "palette":
        return [
            [
                name,
                name,
                name,
                "derived",
                "addons/symbology/initSettings.inc.sqf#symbologyPalette",
            ]
            for name in PALETTES
        ]
    raise SystemExit(f"gen_variation_families: unknown option source {source!r}")


def build_model() -> list[dict]:
    """The family model with each option's derived values."""
    declaration = load(FAMILIES_JSON)
    tables = load(TABLES_JSON)
    modifiers = load(MODIFIERS_JSON)
    families: list[dict] = []
    for family in declaration["families"]:
        options = [
            {
                "id": option["id"],
                "label": option["label"],
                "source": option["source"],
                "values": derive_values(option["source"], tables, modifiers),
            }
            for option in family["options"]
        ]
        families.append(
            {
                "id": family["id"],
                "label": family["label"],
                "entry": family["entry"],
                "markerClass": family["markerClass"],
                "resolver": family["resolver"],
                "options": options,
            }
        )
    return families


def render_config(families: list[dict]) -> str:
    lines = [CONFIG_HEADER.rstrip("\n"), ""]
    for family in families:
        lines.extend(
            [
                f"    class {family['entry']}: AEE_MarkerBase {{",
                f"        name = {sqf_str(family['label'])};",
                f"        icon = {sqf_str(MARKER_PREFIX + chr(92) + ENTRY_TEXTURE)};",
                f"        texture = {sqf_str(MARKER_PREFIX + chr(92) + ENTRY_TEXTURE)};",
                "        side = 2;",
                f"        markerClass = {sqf_str(family['markerClass'])};",
                "        size = 32;",
                "        shadow = 0;",
                "        color[] = {1, 1, 1, 1};",
                "        scope = 2;",
                "    };",
                "",
            ]
        )
    return "\n".join(lines).rstrip("\n") + "\n"


def render_model(families: list[dict]) -> str:
    family_blocks: list[str] = []
    for family in families:
        option_blocks: list[str] = []
        for option in family["options"]:
            values = ",\n".join(
                "            " + sqf_value(value) for value in option["values"]
            )
            option_blocks.append(
                "        ["
                + ", ".join(
                    [
                        sqf_str(option["id"]),
                        sqf_str(option["label"]),
                        sqf_str(option["source"]),
                    ]
                )
                + ", [\n"
                + values
                + "\n        ]]"
            )
        options = ",\n".join(option_blocks)
        family_blocks.append(
            "    ["
            + ", ".join(
                [
                    sqf_str(family["id"]),
                    sqf_str(family["label"]),
                    sqf_str(family["entry"]),
                    sqf_str(family["markerClass"]),
                    sqf_str(family["resolver"]),
                ]
            )
            + ", [\n"
            + options
            + "\n    ]]"
        )
    body = ",\n".join(family_blocks)
    return MODEL_HEADER.rstrip("\n") + "\n\n[\n" + body + "\n]\n"


def artifacts() -> dict[Path, str]:
    families = build_model()
    return {
        CONFIG_OUT: render_config(families),
        MODEL_OUT: render_model(families),
    }


def check() -> int:
    stale: list[str] = []
    for path, content in artifacts().items():
        if not path.is_file():
            stale.append(f"{path.relative_to(ROOT)} is missing")
        elif path.read_text(encoding="utf-8") != content:
            stale.append(f"{path.relative_to(ROOT)} is stale")
    if stale:
        print(f"variation families: FAIL ({len(stale)})")
        for line in stale:
            print(f"  {line}")
        return 1
    print("variation families: config and runtime model fresh")
    return 0


def table() -> int:
    families = build_model()
    for family in families:
        print(
            f"{family['id']}: {family['label']} -> {family['entry']} "
            f"(resolver {family['resolver']})"
        )
        for option in family["options"]:
            print(f"  {option['id']}: {len(option['values'])} values")
    return 0


def build() -> int:
    written = artifacts()
    for path, content in written.items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


def main(argv: list[str]) -> int:
    if "--check" in argv:
        return check()
    if "--table" in argv:
        return table()
    return build()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
