#!/usr/bin/env python3
"""Generate the engine-class ownership sentinels (ADR-027).

ADR-027 detects the silent load-order loss: another mod loads after AEE and
wins the config merge for a class AEE owns.  The detector is a sentinel: one
declared property per engine class AEE owns, read from the live config tree at
init and compared against AEE's declared value.

The source of truth is `data/ownership/sentinels.json`.  This generator emits
`addons/core/data/ownership_sentinels.sqf` (read at preInit into
`aee_core_ownershipSentinels`) and fails when:

  * an expected value no longer appears in the named source file (drift),
  * a type is not one of number/array/text,
  * two sentinels share an id.

Run:
    python3 tools/gen_ownership_sentinels.py           # write the SQF
    python3 tools/gen_ownership_sentinels.py --check   # fail on drift
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).parents[1]
REGISTRY = ROOT / "data" / "ownership" / "sentinels.json"
OUT = ROOT / "addons" / "core" / "data" / "ownership_sentinels.sqf"

TYPES = ("number", "array", "text")

HEADER = """/* SPDX-License-Identifier: GPL-2.0-or-later */
// Generated by tools/gen_ownership_sentinels.py. Do not edit by hand.
// Ownership sentinels (ADR-027): one declared property per engine class AEE
// owns. fnc_dumpState reads each live value and reports a mismatch when it is
// not AEE's, which detects a later-loading mod winning the config merge.
// Each entry: [id, config path, property, type, expected AEE value].
"""


def load_registry() -> dict:
    return json.loads(REGISTRY.read_text(encoding="utf-8"))


def sqf_value(value, value_type: str) -> str:
    if value_type == "number":
        number = float(value)
        return str(int(number)) if number == int(number) else repr(number)
    if value_type == "array":
        return "[" + ", ".join(sqf_value(v, "number") for v in value) + "]"
    if value_type == "text":
        return '"' + str(value).replace('"', '""') + '"'
    raise ValueError(f"unsupported type {value_type!r}")


def audit(registry: dict) -> list[str]:
    errors: list[str] = []
    seen: set[str] = set()
    for entry in registry.get("sentinels", []):
        sid = entry.get("id", "")
        if not sid:
            errors.append("sentinel with no id")
        elif sid in seen:
            errors.append(f"duplicate sentinel id: {sid}")
        seen.add(sid)

        value_type = entry.get("type")
        if value_type not in TYPES:
            errors.append(f"{sid}: invalid type {value_type!r}")
            continue
        if not entry.get("path") or not entry.get("property"):
            errors.append(f"{sid}: empty config path or property")

        source = entry.get("source", "")
        evidence = entry.get("evidence", "")
        src_path = ROOT / source
        if not src_path.exists():
            errors.append(f"{sid}: source file not found: {source}")
        elif evidence and evidence not in src_path.read_text(encoding="utf-8"):
            errors.append(f"{sid}: expected value not found in {source}: {evidence!r}")
    return errors


def build(registry: dict) -> str:
    rows = []
    for entry in registry.get("sentinels", []):
        path = "[" + ", ".join(f'"{name}"' for name in entry["path"]) + "]"
        rows.append(
            "    [{id}, {path}, {prop}, {typ}, {val}]".format(
                id=f'"{entry["id"]}"',
                path=path,
                prop=f'"{entry["property"]}"',
                typ=f'"{entry["type"]}"',
                val=sqf_value(entry["expected"], entry["type"]),
            )
        )
    body = ",\n".join(rows)
    return f"{HEADER}[\n{body}\n]\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail on drift, write nothing"
    )
    args = parser.parse_args()

    registry = load_registry()
    errors = audit(registry)
    if errors:
        for error in errors:
            print(f"ownership sentinels: {error}")
        print("ownership sentinels: FAIL")
        return 1

    generated = build(registry)
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""

    if args.check:
        if current != generated:
            print("ownership sentinels: generated SQF is stale (run without --check)")
            return 1
        print(
            f"ownership sentinels: PASS ({len(registry.get('sentinels', []))} sentinels)"
        )
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(generated, encoding="utf-8")
    print(f"ownership sentinels: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
