//! The AEE development extension.
//!
//! Dev-only. The extension ships in no release artefact (ADR-033). It answers
//! the preInit presence probe from `addons/core`, returns `pong` to `ping`,
//! and hosts the loopback dev console (tasks 11 and 12).
//!
//! The Arma 3 extension ABI is the C interface generated by `#[arma]`:
//! `RVExtension`, `RVExtensionArgs`, `RVExtensionRegisterCallback` and
//! `RVExtensionVersion`. `arma-rs` runs the callback dispatch loop on its own
//! worker thread, so `Context::callback_data` never blocks the engine thread.

use arma_rs::{arma, Extension};

/// The extension name SQF addresses through `callExtension`.
pub const NAME: &str = "aee_dev";

#[arma]
fn init() -> Extension {
    Extension::build()
        .version(env!("CARGO_PKG_VERSION").to_string())
        .command("ping", ping)
        .command("__probe__", probe)
        .finish()
}

/// Returns `pong`.
fn ping() -> String {
    "pong".to_string()
}

/// The preInit presence probe from `fnc_probeExtension.sqf`. Any non-empty
/// return marks the extension ready; the version string is that value.
fn probe() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ping_returns_pong() {
        let (output, code) = init().testing().call("ping", None);
        assert_eq!(code, 0);
        assert_eq!(output, "pong");
    }

    #[test]
    fn presence_probe_is_non_empty() {
        let (output, code) = init().testing().call("__probe__", None);
        assert_eq!(code, 0);
        assert!(!output.is_empty());
    }
}
