//! The AEE development extension.
//!
//! Dev-only. The extension ships in no release artefact (ADR-033). It answers
//! the preInit presence probe from `addons/core`, returns `pong` to `ping`,
//! and hosts the loopback dev console.
//!
//! The Arma 3 extension ABI is the C interface generated by `#[arma]`:
//! `RVExtension`, `RVExtensionArgs`, `RVExtensionRegisterCallback` and
//! `RVExtensionVersion`. `arma-rs` runs the callback dispatch loop on its own
//! worker thread, so `Context::callback_data` never blocks the engine thread.
//!
//! Commands:
//!
//! - `ping` -> `pong`.
//! - `__probe__` -> the version string (the preInit readiness probe).
//! - `start` -> starts the loopback HTTP listener; captures the callback once.
//! - `stop` -> stops the listener.
//! - `reply` -> `["reply", [id, payload]]`, resolves a waiting HTTP request.
//! - `reply_chunk` -> `["reply_chunk", [id, index, chunk, last]]`, reassembles
//!   a reply larger than the chunk bound.

use std::sync::{Arc, LazyLock};
use std::time::Duration;

use arma_rs::{arma, Context, Extension};

pub mod bridge;
pub mod http;
pub mod kernels;

use bridge::{Bridge, BridgeError, BridgeHandler, CallbackChannel, DEFAULT_TIMEOUT};
use http::{DevConfig, DevServer, StartOutcome};

/// The extension name SQF addresses through `callExtension`.
pub const NAME: &str = "aee_dev";

/// The SQF `ExtensionCallback` function name an `exec` request raises.
const EXEC_CALLBACK: &str = "exec";

static BRIDGE: LazyLock<Arc<Bridge>> = LazyLock::new(|| Arc::new(Bridge::new()));
static DEV_SERVER: LazyLock<DevServer> = LazyLock::new(DevServer::new);

#[arma]
fn init() -> Extension {
    Extension::build()
        .version(env!("CARGO_PKG_VERSION").to_string())
        .command("ping", ping)
        .command("__probe__", probe)
        .command("start", start)
        .command("stop", stop)
        .command("reply", reply)
        .command("reply_chunk", reply_chunk)
        .command("kernel.calculateStationPressure", kernel_station_pressure)
        .command("kernel.calculateRelativeHumidity", kernel_relative_humidity)
        .command("kernel.calculateAirDensityKernel", kernel_air_density)
        .command(
            "kernel.calculateBallisticDrag",
            kernel_calculate_ballistic_drag,
        )
        .command("kernel.eyeAdaptStep", kernel_eye_adapt_step)
        .command("kernel.eyeMesopicWeight", kernel_eye_mesopic_weight)
        .command("kernel.eyePupilSteady", kernel_eye_pupil_steady)
        .command("kernel.eyePupilStep", kernel_eye_pupil_step)
        .command("kernel.eyeTimeSkip", kernel_eye_time_skip)
        .command("kernel.solveTwoNodeKernel", kernel_solve_two_node)
        .finish()
}

/// Returns `pong`.
fn ping() -> String {
    "pong".to_string()
}

/// The preInit presence probe from `fnc_probeExtension.sqf`. Any non-empty
/// return marks the extension ready; the version string is that value.
fn probe() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

/// A callback channel backed by the arma-rs `Context`.
struct ArmaCallback {
    context: Context,
}

impl CallbackChannel for ArmaCallback {
    fn exec(&self, request: &str) -> Result<(), BridgeError> {
        self.context
            .callback_data(NAME, EXEC_CALLBACK, request.to_string())
            .map_err(|_| BridgeError::CallbackClosed)
    }
}

/// Starts the loopback listener. The callback is captured once, here, in the
/// handler factory the server runs exactly once at start.
fn start(context: Context) -> String {
    let config = DevConfig::from_env();
    let bridge = Arc::clone(&BRIDGE);
    let timeout = reply_timeout();
    match DEV_SERVER.start(&config, move || {
        let callback: Arc<dyn CallbackChannel> = Arc::new(ArmaCallback { context });
        Arc::new(BridgeHandler::new(bridge, callback, timeout))
    }) {
        Ok(StartOutcome::Started(addr)) => format!("started {addr}"),
        Ok(StartOutcome::AlreadyRunning) => "already-running".to_string(),
        Ok(StartOutcome::DisabledInClientBuild) => {
            "error: dev listener disabled in a client build".to_string()
        }
        Err(error) => format!("error: {error}"),
    }
}

/// Stops the listener.
fn stop() -> String {
    if DEV_SERVER.stop() {
        "stopped".to_string()
    } else {
        "not-running".to_string()
    }
}

/// Stores a complete reply for `id` and unblocks the waiting HTTP thread.
fn reply(id: f64, payload: String) -> String {
    match BRIDGE.reply(as_id(id), payload) {
        Ok(()) => "ok".to_string(),
        Err(error) => format!("error: {error}"),
    }
}

/// Stores one chunk of a reply larger than the chunk bound.
fn reply_chunk(id: f64, index: f64, chunk: String, last: bool) -> String {
    match BRIDGE.reply_chunk(as_id(id), as_index(index), chunk, last) {
        Ok(()) => "ok".to_string(),
        Err(error) => format!("error: {error}"),
    }
}

/// Station pressure. The SQF dispatcher maps `kernel.calculateStationPressure`
/// to [`kernels::station_pressure`]; the same call is the parity oracle.
fn kernel_station_pressure(p_sea: f64, elevation: f64, lapse_rate: f64) -> String {
    kernels::station_pressure(p_sea, elevation, lapse_rate).to_string()
}

/// Relative humidity. Dispatcher name `kernel.calculateRelativeHumidity`.
fn kernel_relative_humidity(
    rh_base: f64,
    surface_mod: f64,
    t_ref: f64,
    t_now: f64,
    overcast: f64,
    rain: f64,
) -> String {
    kernels::relative_humidity(rh_base, surface_mod, t_ref, t_now, overcast, rain).to_string()
}

/// Air density. Dispatcher name `kernel.calculateAirDensity`.
#[must_use]
fn kernel_air_density(t_c: f64, p_hpa: f64, rh: f64) -> String {
    kernels::air_density(t_c, p_hpa, rh).to_string()
}

/// Ballistic drag. Dispatcher name `kernel.calculateBallisticDrag`. The
/// driver forwards the resolved drag-model name; the SQF kernel stays the
/// fallback and uppercases a string name the same way.
fn kernel_calculate_ballistic_drag(
    bc: f64,
    velocity: f64,
    drag_model: String,
    rho_rel: f64,
    air_temp_c: f64,
) -> String {
    kernels::calculate_ballistic_drag(bc, velocity, &drag_model, rho_rel, air_temp_c).to_string()
}

/// Eye adaptation step. Dispatcher name `kernel.eyeAdaptStep`. Returns
/// `[cone, rod]` as an SQF array string.
fn kernel_eye_adapt_step(
    state: Vec<f64>,
    target_log_lum: f64,
    dt: f64,
    tau_light: f64,
    tau_dark_cone: f64,
    tau_dark_rod: f64,
    w: f64,
) -> String {
    let (cone, rod) = kernels::eye_adapt_step(
        &state,
        target_log_lum,
        dt,
        tau_light,
        tau_dark_cone,
        tau_dark_rod,
        w,
    );
    format!("[{cone},{rod}]")
}

/// Eye mesopic photopic fraction. Dispatcher name `kernel.eyeMesopicWeight`.
fn kernel_eye_mesopic_weight(lum: f64, lo: f64, hi: f64) -> String {
    kernels::eye_mesopic_weight(lum, lo, hi).to_string()
}

/// Steady pupil diameter. Dispatcher name `kernel.eyePupilSteady`.
fn kernel_eye_pupil_steady(lum: f64) -> String {
    kernels::eye_pupil_steady(lum).to_string()
}

/// Pupil lag step. Dispatcher name `kernel.eyePupilStep`.
fn kernel_eye_pupil_step(
    d: f64,
    d_target: f64,
    dt: f64,
    tau_constrict: f64,
    tau_dilate: f64,
) -> String {
    kernels::eye_pupil_step(d, d_target, dt, tau_constrict, tau_dilate).to_string()
}

/// Clock-jump detector. Dispatcher name `kernel.eyeTimeSkip`.
fn kernel_eye_time_skip(prev_hour: f64, now_hour: f64, threshold_hours: f64) -> String {
    kernels::eye_time_skip(prev_hour, now_hour, threshold_hours).to_string()
}

/// Two-node thermal solve. Dispatcher name `kernel.solveTwoNodeKernel`. Returns
/// `[core, skin, humanCore]` as an SQF array string. The driver normalises it.
#[allow(clippy::too_many_arguments)]
fn kernel_solve_two_node(
    t_air: f64,
    wind: f64,
    solar: f64,
    exposure: f64,
    m_core: f64,
    m_skin: f64,
    area: f64,
    l_char: f64,
    t_core0: f64,
    t_skin0: f64,
    q_gen: f64,
    orientation: String,
    rh: f64,
    mrt_c: f64,
    is_human: bool,
    evap_on: bool,
    dt: f64,
    water_speed: f64,
    t_water: f64,
    rain: f64,
    skin_perfusion: f64,
    clo: f64,
    cond: f64,
    skin_eps: f64,
    skin_alpha: f64,
) -> String {
    let (core, skin, body) = kernels::solve_two_node(
        t_air,
        wind,
        solar,
        exposure,
        m_core,
        m_skin,
        area,
        l_char,
        t_core0,
        t_skin0,
        q_gen,
        &orientation,
        rh,
        mrt_c,
        is_human,
        evap_on,
        dt,
        water_speed,
        t_water,
        rain,
        skin_perfusion,
        clo,
        cond,
        skin_eps,
        skin_alpha,
    );
    format!("[{core},{skin},{body}]")
}

fn reply_timeout() -> Duration {
    std::env::var("AEE_DEV_TIMEOUT_MS")
        .ok()
        .and_then(|value| value.parse().ok())
        .map(Duration::from_millis)
        .unwrap_or(DEFAULT_TIMEOUT)
}

fn as_id(id: f64) -> u64 {
    if id.is_finite() && id >= 0.0 {
        id as u64
    } else {
        0
    }
}

fn as_index(index: f64) -> u32 {
    if index.is_finite() && index >= 0.0 {
        index as u32
    } else {
        0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ping_returns_pong() {
        let (output, code) = init().testing().call("ping", None);
        assert_eq!(code, 0);
        assert_eq!(output, "pong");
    }

    #[test]
    fn presence_probe_is_non_empty() {
        let (output, code) = init().testing().call("__probe__", None);
        assert_eq!(code, 0);
        assert!(!output.is_empty());
    }

    #[test]
    fn reply_command_resolves_a_pending_id() {
        let (id, rx) = BRIDGE.open();
        assert_eq!(reply(id as f64, "engine-answer".to_string()), "ok");
        assert_eq!(
            bridge::wait(&rx, DEFAULT_TIMEOUT).expect("wait"),
            "engine-answer"
        );
    }

    #[test]
    fn reply_command_reports_an_unknown_id() {
        assert!(reply(9999.0, "x".to_string()).starts_with("error:"));
    }

    /// A parity vector for one native kernel, generated from the SQF reference
    /// by `tools/gen_kernel_vectors.py`.  Arguments are mixed (numbers, strings,
    /// booleans) and the expected value is a scalar or an array.
    #[derive(serde::Deserialize)]
    struct KernelVector {
        args: Vec<serde_json::Value>,
        expected: serde_json::Value,
    }

    /// One kernel's vectors and its justified parity bound (ADR-034).
    #[derive(serde::Deserialize)]
    struct KernelSuite {
        command: String,
        tolerance_rel: f64,
        tolerance_abs: f64,
        vectors: Vec<KernelVector>,
    }

    /// The generated vector file.
    #[derive(serde::Deserialize)]
    struct KernelVectors {
        kernels: std::collections::BTreeMap<String, KernelSuite>,
    }

    const KERNEL_VECTORS: &str = include_str!("../tests/vectors/kernels.json");

    /// The SQF literal form of a generated argument, as `callExtension` passes
    /// it to the extension.
    fn arg_to_string(value: &serde_json::Value) -> String {
        match value {
            serde_json::Value::String(s) => s.clone(),
            serde_json::Value::Bool(b) => b.to_string(),
            other => other.to_string(),
        }
    }

    /// Parse the SQF array string `[a,b,c]` the native array kernel returns.
    fn parse_output_array(output: &str) -> Vec<f64> {
        output
            .trim()
            .trim_start_matches('[')
            .trim_end_matches(']')
            .split(',')
            .map(|item| {
                item.trim()
                    .parse::<f64>()
                    .unwrap_or_else(|_| panic!("non-numeric array element {item:?}"))
            })
            .collect()
    }

    /// Every native kernel matches its SQF reference on the generated vectors.
    #[test]
    fn native_kernels_match_the_sqf_reference() {
        let suite: KernelVectors =
            serde_json::from_str(KERNEL_VECTORS).expect("the vector file parses");
        assert!(!suite.kernels.is_empty(), "no kernel vectors found");
        for (name, kernel) in &suite.kernels {
            for case in &kernel.vectors {
                let args: Vec<String> = case.args.iter().map(arg_to_string).collect();
                let (output, code) = init().testing().call(&kernel.command, Some(args));
                assert_eq!(code, 0, "{name}: the native call failed");
                match &case.expected {
                    serde_json::Value::Number(_) => {
                        let expected = case.expected.as_f64().expect("a number");
                        let actual: f64 = output
                            .parse()
                            .unwrap_or_else(|_| panic!("{name}: non-numeric output {output}"));
                        let bound = kernel.tolerance_abs + kernel.tolerance_rel * expected.abs();
                        assert!(
                            (expected - actual).abs() <= bound,
                            "{name}: expected {expected}, got {actual} (bound {bound})"
                        );
                    }
                    serde_json::Value::Array(items) => {
                        let actuals = parse_output_array(&output);
                        assert_eq!(actuals.len(), items.len(), "{name}: array length");
                        for (index, expected_value) in items.iter().enumerate() {
                            let expected = expected_value.as_f64().expect("a number");
                            let actual = actuals[index];
                            let bound =
                                kernel.tolerance_abs + kernel.tolerance_rel * expected.abs();
                            assert!(
                                (expected - actual).abs() <= bound,
                                "{name}[{index}]: expected {expected}, got {actual} (bound {bound})"
                            );
                        }
                    }
                    serde_json::Value::Bool(expected) => {
                        // A boolean kernel (eyeTimeSkip) returns "true"/"false".
                        let actual = output
                            .trim()
                            .parse::<bool>()
                            .unwrap_or_else(|_| panic!("{name}: non-boolean output {output}"));
                        assert_eq!(
                            *expected, actual,
                            "{name}: expected {expected}, got {actual}"
                        );
                    }
                    other => panic!("{name}: unexpected expected value {other}"),
                }
            }
        }
    }
}
