name: Lint

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  hemtt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arma-actions/hemtt@v1
      - name: Pedantic check, errors on warnings
        run: hemtt check -p -e
